<?php
// airports data: http://ourairports.com/data/

function getAirportInfo($airportCode) {

	if(strlen($airportCode) == 4) {
		$airportCode = $GLOBALS['airportsIcaoToIata'][$airportCode];
	}

	return $GLOBALS['airportsInfo'][$airportCode];
}

$airportsIcaoToIata = array (
	'AYPY'=>'POM',
	'BIKF'=>'KEF',
	'BKPR'=>'PRN',
	'CYEG'=>'YEG',
	'CYHZ'=>'YHZ',
	'CYOW'=>'YOW',
	'CYQB'=>'YQB',
	'CYUL'=>'YUL',
	'CYVR'=>'YVR',
	'CYWG'=>'YWG',
	'CYXU'=>'YXU',
	'CYYC'=>'YYC',
	'CYYJ'=>'YYJ',
	'CYYT'=>'YYT',
	'CYYZ'=>'YYZ',
	'DAAG'=>'ALG',
	'DGAA'=>'ACC',
	'DNAA'=>'ABV',
	'DNAI'=>'QUO',
	'DNMM'=>'LOS',
	'DTTA'=>'TUN',
	'EBBR'=>'BRU',
	'EBCI'=>'CRL',
	'EBLG'=>'LGG',
	'EDDB'=>'SXF',
	'EDDC'=>'DRS',
	'EDDF'=>'FRA',
	'EDDG'=>'FMO',
	'EDDH'=>'HAM',
	'EDDK'=>'CGN',
	'EDDL'=>'DUS',
	'EDDM'=>'MUC',
	'EDDN'=>'NUE',
	'EDDP'=>'LEJ',
	'EDDS'=>'STR',
	'EDDT'=>'TXL',
	'EDDV'=>'HAJ',
	'EDDW'=>'BRE',
	'EDLW'=>'DTM',
	'EDSB'=>'FKB',
	'EETN'=>'TLL',
	'EFHK'=>'HEL',
	'EGAA'=>'BFS',
	'EGAC'=>'BHD',
	'EGBB'=>'BHX',
	'EGCC'=>'MAN',
	'EGCN'=>'DSA',
	'EGFF'=>'CWL',
	'EGGD'=>'BRS',
	'EGGP'=>'LPL',
	'EGGW'=>'LTN',
	'EGHH'=>'BOH',
	'EGHI'=>'SOU',
	'EGKK'=>'LGW',
	'EGLC'=>'LCY',
	'EGLL'=>'LHR',
	'EGNM'=>'LBA',
	'EGNT'=>'NCL',
	'EGNX'=>'EMA',
	'EGPD'=>'ABZ',
	'EGPF'=>'GLA',
	'EGPH'=>'EDI',
	'EGSH'=>'NWI',
	'EGSS'=>'STN',
	'EGTE'=>'EXT',
	'EGUL'=>'LKZ',
	'EGUN'=>'MHZ',
	'EGVA'=>'FFD',
	'EGVN'=>'BZZ',
	'EHAM'=>'AMS',
	'EHBK'=>'MST',
	'EHEH'=>'EIN',
	'EICK'=>'ORK',
	'EIDW'=>'DUB',
	'EINN'=>'SNN',
	'EKBI'=>'BLL',
	'EKCH'=>'CPH',
	'EKYT'=>'AAL',
	'ELLX'=>'LUX',
	'ENBO'=>'BOO',
	'ENBR'=>'BGO',
	'ENGM'=>'OSL',
	'ENTC'=>'TOS',
	'ENVA'=>'TRD',
	'ENZV'=>'SVG',
	'EPGD'=>'GDN',
	'EPKK'=>'KRK',
	'EPKT'=>'KTW',
	'EPMO'=>'WMI',
	'EPPO'=>'POZ',
	'EPWA'=>'WAW',
	'EPWR'=>'WRO',
	'ESGG'=>'GOT',
	'ESMS'=>'MMX',
	'ESPA'=>'LLA',
	'ESSA'=>'ARN',
	'ETAR'=>'RMS',
	'EVRA'=>'RIX',
	'EYVI'=>'VNO',
	'FACT'=>'CPT',
	'FAGG'=>'GRJ',
	'FAOR'=>'JNB',
	'FALE'=>'DUR',
	//BeR 4Apr18: adding manually Mauritius MRU airport
	'FIMP'=>'MRU',
	'GCLP'=>'LPA',
	'GCTS'=>'TFS',
	'GCXO'=>'TFN',
	'GMMN'=>'CMN',
	'GOOY'=>'DKR',
	'HAAB'=>'ADD',
	'HECA'=>'CAI',
	'HEGN'=>'HRG',
	'HKJK'=>'NBO',
	'HKMO'=>'MBA',
	'HLLT'=>'TIP',
	'HSSJ'=>'JUB',
	'HSSS'=>'KRT',
	'WIMM'=>'KNO',
	'KABQ'=>'ABQ',
	'KADW'=>'ADW',
	'KAFW'=>'AFW',
	'KAGS'=>'AGS',
	'KAMA'=>'AMA',
	'KATL'=>'ATL',
	'KAUS'=>'AUS',
	'KAVL'=>'AVL',
	'KBAB'=>'BAB',
	'KBAD'=>'BAD',
	'KBDL'=>'BDL',
	'KBFI'=>'BFI',
	'KBGR'=>'BGR',
	'KBHM'=>'BHM',
	'KBIL'=>'BIL',
	'KBLV'=>'BLV',
	'KBMI'=>'BMI',
	'KBNA'=>'BNA',
	'KBOI'=>'BOI',
	'KBOS'=>'BOS',
	'KBTR'=>'BTR',
	'KBUF'=>'BUF',
	'KBWI'=>'BWI',
	'KCAE'=>'CAE',
	'KCBM'=>'CBM',
	'KCHA'=>'CHA',
	'KCHS'=>'CHS',
	'KCID'=>'CID',
	'KCLE'=>'CLE',
	'KCLT'=>'CLT',
	'KCMH'=>'CMH',
	'KCOS'=>'COS',
	'KCPR'=>'CPR',
	'KCRP'=>'CRP',
	'KCRW'=>'CRW',
	'KCVG'=>'CVG',
	'KCVS'=>'CVS',
	'KDAL'=>'DAL',
	'KDAY'=>'DAY',
	'KDBQ'=>'DBQ',
	'KDCA'=>'DCA',
	'KDEN'=>'DEN',
	'KDFW'=>'DFW',
	'KDLF'=>'DLF',
	'KDLH'=>'DLH',
	'KDOV'=>'DOV',
	'KDSM'=>'DSM',
	'KDTW'=>'DTW',
	'KDYS'=>'DYS',
	'KEDW'=>'',
	'KEND'=>'END',
	'KERI'=>'ERI',
	'KEWR'=>'EWR',
	'KFFO'=>'FFO',
	'KFLL'=>'FLL',
	'KFSM'=>'FSM',
	'KFTW'=>'FTW',
	'KFWA'=>'FWA',
	'KGEG'=>'GEG',
	'KGPT'=>'GPT',
	'KGRB'=>'GRB',
	'KGSB'=>'GSB',
	'KGSO'=>'GSO',
	'KGSP'=>'GSP',
	'KGUS'=>'GUS',
	'KHIB'=>'HIB',
	'KHMN'=>'HMN',
	'KHOU'=>'HOU',
	'KHSV'=>'HSV',
	'KHTS'=>'HTS',
	'KIAD'=>'IAD',
	'KIAH'=>'IAH',
	'KICT'=>'ICT',
	'KIND'=>'IND',
	'KJAN'=>'JAN',
	'KJAX'=>'JAX',
	'KJFK'=>'JFK',
	'KJLN'=>'JLN',
	'KLAS'=>'LAS',
	'KLAX'=>'LAX',
	'KLBB'=>'LBB',
	'KLCK'=>'LCK',
	'KLEX'=>'LEX',
	'KLFI'=>'LFI',
	'KLFT'=>'LFT',
	'KLGA'=>'LGA',
	'KLIT'=>'LIT',
	'KLTS'=>'LTS',
	'KLUF'=>'LUF',
	'KMBS'=>'MBS',
	'KMCF'=>'MCF',
	'KMCI'=>'MCI',
	'KMCO'=>'MCO',
	'KMDW'=>'MDW',
	'KMEM'=>'MEM',
	'KMGE'=>'MGE',
	'KMGM'=>'MGM',
	'KMHT'=>'MHT',
	'KMIA'=>'MIA',
	'KMKE'=>'MKE',
	'KMLI'=>'MLI',
	'KMLU'=>'MLU',
	'KMOB'=>'MOB',
	'KMSN'=>'MSN',
	'KMSP'=>'MSP',
	'KMSY'=>'MSY',
	'KMUO'=>'',
	'KOAK'=>'OAK',
	'KOKC'=>'OKC',
	'KONT'=>'ONT',
	'KORD'=>'ORD',
	'KORF'=>'ORF',
	'KPAM'=>'PAM',
	'KPBI'=>'PBI',
	'KPDX'=>'PDX',
	'KPHF'=>'PHF',
	'KPHL'=>'PHL',
	'KPHX'=>'PHX',
	'KPIA'=>'PIA',
	'KPIT'=>'PIT',
	'KPWM'=>'PWM',
	'KRDU'=>'RDU',
	'KRFD'=>'RFD',
	'KRIC'=>'RIC',
	'KRND'=>'RND',
	'KRNO'=>'RNO',
	'KROA'=>'ROA',
	'KROC'=>'ROC',
	'KRST'=>'RST',
	'KRSW'=>'RSW',
	'KSAN'=>'SAN',
	'KSAT'=>'SAT',
	'KSAV'=>'SAV',
	'KSBN'=>'SBN',
	'KSDF'=>'SDF',
	'KSEA'=>'SEA',
	'KSFB'=>'SFB',
	'KSFO'=>'SFO',
	'KSGF'=>'SGF',
	'KSHV'=>'SHV',
	'KSJC'=>'SJC',
	'KSKA'=>'SKA',
	'KSLC'=>'SLC',
	'KSMF'=>'SMF',
	'KSNA'=>'SNA',
	'KSPI'=>'SPI',
	'KSPS'=>'SPS',
	'KSRQ'=>'SRQ',
	'KSSC'=>'SSC',
	'KSTL'=>'STL',
	'KSUS'=>'SUS',
	'KSUU'=>'SUU',
	'KSUX'=>'SUX',
	'KSYR'=>'SYR',
	'KSZL'=>'SZL',
	'KTCM'=>'TCM',
	'KTIK'=>'TIK',
	'KTLH'=>'TLH',
	'KTOL'=>'TOL',
	'KTPA'=>'TPA',
	'KTRI'=>'TRI',
	'KTUL'=>'TUL',
	'KTUS'=>'TUS',
	'KTYS'=>'TYS',
	'KVBG'=>'VBG',
	'KVPS'=>'VPS',
	'KWRB'=>'WRB',
	'LATI'=>'TIA',
	'LBBG'=>'BOJ',
	'LBPD'=>'PDV',
	'LBSF'=>'SOF',
	'LBWN'=>'VAR',
	'LCLK'=>'LCA',
	'LCPH'=>'PFO',
	'LDZA'=>'ZAG',
	'LEAL'=>'ALC',
	'LEBL'=>'BCN',
	'LEMD'=>'MAD',
	'LEMG'=>'AGP',
	'LEPA'=>'PMI',
	'LEST'=>'SCQ',
	'LFBD'=>'BOD',
	'LFBO'=>'TLS',
	'LFML'=>'MRS',
	'LFMN'=>'NCE',
	'LFOA'=>'',
	'LFPG'=>'CDG',
	'LFPO'=>'ORY',
	'LFSB'=>'BSL',
	'LGAV'=>'ATH',
	'LGIR'=>'HER',
	'LGTS'=>'SKG',
	'LHBP'=>'BUD',
	'LIBD'=>'BRI',
	'LICC'=>'CTA',
	'LICJ'=>'PMO',
	'LIEE'=>'CAG',
	'LIMC'=>'MXP',
	'LIME'=>'BGY',
	'LIMF'=>'TRN',
	'LIMJ'=>'GOA',
	'LIML'=>'LIN',
	'LIMZ'=>'CUF',
	'LIPE'=>'BLQ',
	'LIPH'=>'TSF',
	'LIPX'=>'VRN',
	'LIPZ'=>'VCE',
	'LIRA'=>'CIA',
	'LIRF'=>'FCO',
	'LIRN'=>'NAP',
	'LIRP'=>'PSA',
	'LJLJ'=>'LJU',
	'LKPR'=>'PRG',
	'LLBG'=>'TLV',
	'LLOV'=>'VDA',
	'LMML'=>'MLA',
	'LOWW'=>'VIE',
	'LPFR'=>'FAO',
	'LPLA'=>'TER',
	'LPPD'=>'PDL',
	'LPPR'=>'OPO',
	'LPPT'=>'LIS',
	'LQSA'=>'SJJ',
	'LROP'=>'OTP',
	'LSGG'=>'GVA',
	'LSZH'=>'ZRH',
	'LTAC'=>'ESB',
	'LTAF'=>'ADA',
	'LTAI'=>'AYT',
	'LTAJ'=>'GZT',
	'LTAZ'=>'NAV',
	'LTBA'=>'IST',
	'LTBJ'=>'ADB',
	'LTBS'=>'DLM',
	'LTCE'=>'ERZ',
	'LTCG'=>'TZX',
	'LTFC'=>'ISE',
	'LTFE'=>'BJV',
	'LTFJ'=>'SAW',
	'LYBE'=>'BEG',
	'LYPG'=>'TGD',
	'LZIB'=>'BTS',
	'MDPC'=>'PUJ',
	'MDSD'=>'SDQ',
	'MKJP'=>'KIN',
	'MMAA'=>'ACA',
	'MMGL'=>'GDL',
	'MMHO'=>'HMO',
	'MMMX'=>'MEX',
	'MMMY'=>'MTY',
	'MMPR'=>'PVR',
	'MMSD'=>'SJD',
	'MMTJ'=>'TIJ',
	'MMUN'=>'CUN',
	'MPTO'=>'PTY',
	'MUHA'=>'HAV',
	'MUVR'=>'VRA',
	'MWCR'=>'GCM',
	'MYNN'=>'NAS',
	'MZBZ'=>'BZE',
	'NCRG'=>'RAR',
	'NZAA'=>'AKL',
	'NZCH'=>'CHC',
	'NZWN'=>'WLG',
	'OBBI'=>'BAH',
	'OEDF'=>'DMM',
	'OEDR'=>'DHA',
	'OEJN'=>'JED',
	'OEMA'=>'MED',
	'OERK'=>'RUH',
	'OIIE'=>'IKA',
	'OIII'=>'THR',
	'OIMM'=>'MHD',
	'OISS'=>'SYZ',
	'OITT'=>'TBZ',
	'OJAI'=>'AMM',
	'OKBK'=>'KWI',
	'OLBA'=>'BEY',
	'OODQ'=>'DQM',
	'OORQ'=>'',
	'OMAA'=>'AUH',
	'OMDB'=>'DXB',
	'OMDW'=>'DWC',
	'OMSJ'=>'SHJ',
	'OOMS'=>'MCT',
	'OPRN'=>'ISB',
	'OPST'=>'SKT',
	'ORBI'=>'BGW',
	'ORMM'=>'BSR',
	'OSAP'=>'ALP',
	'OSDI'=>'DAM',
	'OSLK'=>'LTK',
	'PAFA'=>'FAI',
	'PANC'=>'ANC',
	'PGUM'=>'GUM',
	'RPMY'=>'CGY',
	'PHNL'=>'HNL',	
	'OOSA' =>'SLL',
	'OTHH'=>'DOH',
	'RCBS'=>'KNH',
	'RCKH'=>'KHH',
	'RCTP'=>'TPE',
	'RJAA'=>'NRT',
	'RJBB'=>'KIX',
	'RJCC'=>'CTS',
	'RJFF'=>'FUK',
	'RJFK'=>'KOJ',
	'RJGG'=>'NGO',
	'RJNS'=>'FSZ',
	'RJOO'=>'ITM',
	'RJTT'=>'HND',
	'RJTY'=>'OKO',
	'RKJB'=>'MWX',
	'RKJK'=>'KUV',
	'RKPC'=>'CJU',
	'RKPK'=>'PUS',
	'RKSI'=>'ICN',
	'RKSO'=>'OSN',
	'RKSS'=>'GMP',
	'RKTU'=>'CJJ',
	'ROAH'=>'OKA',
	'RODN'=>'DNA',
	'RPLC'=>'CRK',
	'RPLL'=>'MNL',
	'RPMD'=>'DVO',
	'RPVM'=>'CEB',
	'URMG'=>'GRV',
	'SAEZ'=>'EZE',
	'SBBE'=>'BEL',
	'SBBR'=>'BSB',
	'SBCF'=>'CNF',
	'SBCT'=>'CWB',
	'SBFL'=>'FLN',
	'SBGL'=>'GIG',
	'SBGR'=>'GRU',
	'SBSG'=>'NAT',
	'SBSP'=>'CGH',
	'SBSV'=>'SSA',
	'SCEL'=>'SCL',
	'SELT'=>'LTX',
	'SEQM'=>'UIO',
	'SKBO'=>'BOG',
	'SPIM'=>'LIM',
	'SPZO'=>'CUZ',
	'SUMU'=>'MVD',
	'TJSJ'=>'SJU',
	'DTNH'=>'NBE',
	'TNCM'=>'SXM',
	'UAAA'=>'ALA',
	'UACC'=>'TSE',
	'UCFM'=>'FRU',
	'UAKK'=>'KGF',
	'UBBB'=>'GYD',
	'UDYZ'=>'EVN',
	'UGTB'=>'TBS',
	'UHHH'=>'KHV',
	'UKBB'=>'KBP',
	'UKCC'=>'DOK',
	'UKFF'=>'SIP',
	'UKHH'=>'HRK',
	'UKOO'=>'ODS',
	'ULLI'=>'LED',
	'UMMS'=>'MSQ',
	'UNKL'=>'KJA',
	'UNNT'=>'OVB',
	'URRR'=>'ROV',
	'URSS'=>'AER',
	'USSS'=>'SVX',
	'UTTT'=>'TAS',
	'UUBW'=>'',
	'UUDD'=>'DME',
	'UUEE'=>'SVO',
	'UUMU'=>'CKL',
	'UUWW'=>'VKO',
	'UWKD'=>'KZN',
	'UWKG'=>'',
	'UWUU'=>'UFA',
	'UWWW'=>'KUF',
	'VABB'=>'BOM',
	'VOGO'=>'GOI',
	'VCBI'=>'CMB',
	'VCRI'=>'HRI',
	'VDPP'=>'PNH',
	'VDSR'=>'REP',
	'VECC'=>'CCU',
	'VHHH'=>'HKG',
	'VIAR'=>'ATQ',
	'VIDP'=>'DEL',
	'VISM'=>'SLV',
	'VMMC'=>'MFM',
	'VOBL'=>'BLR',
	'VOCI'=>'COK',
	'VOCL'=>'CCJ',
	'VOHS'=>'HYD',
	'VOMM'=>'MAA',
	'VOTV'=>'TRV',
	'VRMM'=>'MLE',
	'VTBD'=>'DMK',
	'VTBS'=>'BKK',
	'VTCC'=>'CNX',
	'VVDN'=>'DAD',
	'VVNB'=>'HAN',
	'VVTS'=>'SGN',
	'VYMD'=>'MDL',
	'VYYY'=>'RGN',
	'WAAA'=>'UPG',
	'WADD'=>'DPS',
	'WARR'=>'SUB',
	'WASS'=>'SOQ',
	'WBSB'=>'BWN',
	'WIII'=>'CGK',
	'WMKK'=>'KUL',
	'WSSS'=>'SIN',
	'YBBN'=>'BNE',
	'YMML'=>'MEL',
	'YPPH'=>'PER',
	'YSCB'=>'CBR',
	'YSSY'=>'SYD',
	'ZBAA'=>'PEK',
	'ZBNY'=>'NAY',
	'ZBTJ'=>'TSN',
	'ZBYN'=>'TYN',
	'ZGGG'=>'CAN',
	'ZGHA'=>'CSX',
	'ZGKL'=>'KWL',
	'ZGNN'=>'NNG',
	'ZGSZ'=>'SZX',
	'ZHCC'=>'CGO',
	'ZHHH'=>'WUH',
	'ZJHK'=>'HAK',
	'ZJSY'=>'SYX',
	'ZLXY'=>'XIY',
	'ZPPP'=>'KMG',
	'ZSAM'=>'XMN',
	'ZSFZ'=>'FOC',
	'ZSHC'=>'HGH',
	'ZSJN'=>'TNA',
	'ZSNB'=>'NGB',
	'ZSNJ'=>'NKG',
	'ZSPD'=>'PVG',
	'ZSSS'=>'SHA',
	'ZSWZ'=>'WNZ',
	'ZUCK'=>'CKG',
	'ZUGY'=>'KWE',
	'ZUUU'=>'CTU',
	'ZWWW'=>'URC',
	'ZYHB'=>'HRB',
	'ZYTL'=>'DLC',
	'ZYTX'=>'SHE'
);

$airportsInfo = array (
	'POM'=> array('name' => 'Port Moresby Jacksons International Airport', 'municipality' => 'Port Moresby', 'lat' =>	-9.44	, 'long' =>	147.22	, 'elevation' =>	146	),	
	'KEF'=> array('name' => 'Keflavik International Airport', 'municipality' => 'Reykjav��k', 'lat' =>	63.99	, 'long' =>	-22.61	, 'elevation' =>	171	),	
	'PRN'=> array('name' => 'Prishtina International Airport', 'municipality' => 'Prishtina', 'lat' =>	42.57	, 'long' =>	21.04	, 'elevation' =>	1789	),	
	'YEG'=> array('name' => 'Edmonton International Airport', 'municipality' => 'Edmonton', 'lat' =>	53.31	, 'long' =>	-113.58	, 'elevation' =>	2373	),	
	'YHZ'=> array('name' => 'Halifax / Stanfield International Airport', 'municipality' => 'Halifax', 'lat' =>	44.88	, 'long' =>	-63.51	, 'elevation' =>	477	),	
	'YOW'=> array('name' => 'Ottawa Macdonald-Cartier International Airport', 'municipality' => 'Ottawa', 'lat' =>	45.32	, 'long' =>	-75.67	, 'elevation' =>	374	),	
	'YQB'=> array('name' => 'Quebec Jean Lesage International Airport', 'municipality' => 'Quebec', 'lat' =>	46.79	, 'long' =>	-71.39	, 'elevation' =>	244	),	
	'YUL'=> array('name' => 'Montreal / Pierre Elliott Trudeau International Airport', 'municipality' => 'Montreal', 'lat' =>	45.47	, 'long' =>	-73.74	, 'elevation' =>	118	),	
	'YVR'=> array('name' => 'Vancouver International Airport', 'municipality' => 'Vancouver', 'lat' =>	49.19	, 'long' =>	-123.18	, 'elevation' =>	14	),	
	'YWG'=> array('name' => 'Winnipeg / James Armstrong Richardson International Airport', 'municipality' => 'Winnipeg', 'lat' =>	49.91	, 'long' =>	-97.24	, 'elevation' =>	783	),	
	'YXU'=> array('name' => 'London Airport', 'municipality' => 'London', 'lat' =>	43.04	, 'long' =>	-81.15	, 'elevation' =>	912	),	
	'YYC'=> array('name' => 'Calgary International Airport', 'municipality' => 'Calgary', 'lat' =>	51.11	, 'long' =>	-114.02	, 'elevation' =>	3557	),	
	'YYJ'=> array('name' => 'Victoria International Airport', 'municipality' => 'Victoria', 'lat' =>	48.65	, 'long' =>	-123.43	, 'elevation' =>	63	),	
	'YYT'=> array('name' => 'St. John\'s International Airport', 'municipality' => 'St. John\'s', 'lat' =>	47.62	, 'long' =>	-52.75	, 'elevation' =>	461	),	
	'YYZ'=> array('name' => 'Lester B. Pearson International Airport', 'municipality' => 'Toronto', 'lat' =>	43.68	, 'long' =>	-79.63	, 'elevation' =>	569	),	
	'ALG'=> array('name' => 'Houari Boumediene Airport', 'municipality' => 'Algiers', 'lat' =>	36.69	, 'long' =>	3.22	, 'elevation' =>	82	),	
	'ACC'=> array('name' => 'Kotoka International Airport', 'municipality' => 'Accra', 'lat' =>	5.61	, 'long' =>	-0.17	, 'elevation' =>	205	),	
	'ABV'=> array('name' => 'Nnamdi Azikiwe International Airport', 'municipality' => 'Abuja', 'lat' =>	9.01	, 'long' =>	7.26	, 'elevation' =>	1123	),	
	'QUO'=> array('name' => 'Akwa Ibom International Airport', 'municipality' => 'Uyo', 'lat' =>	4.87	, 'long' =>	8.09	, 'elevation' =>	170	),	
	'LOS'=> array('name' => 'Murtala Muhammed International Airport', 'municipality' => 'Lagos', 'lat' =>	6.58	, 'long' =>	3.32	, 'elevation' =>	135	),	
	'TUN'=> array('name' => 'Tunis Carthage International Airport', 'municipality' => 'Tunis', 'lat' =>	36.85	, 'long' =>	10.23	, 'elevation' =>	22	),	
	'BRU'=> array('name' => 'Brussels Airport', 'municipality' => 'Brussels', 'lat' =>	50.90	, 'long' =>	4.48	, 'elevation' =>	184	),	
	'CRL'=> array('name' => 'Brussels South Charleroi Airport', 'municipality' => 'Brussels', 'lat' =>	50.46	, 'long' =>	4.45	, 'elevation' =>	614	),	
	'LGG'=> array('name' => 'Liege Airport', 'municipality' => 'Li��ge', 'lat' =>	50.64	, 'long' =>	5.44	, 'elevation' =>	659	),	
	'SXF'=> array('name' => 'Berlin-Sch��nefeld International Airport', 'municipality' => 'Berlin', 'lat' =>	52.38	, 'long' =>	13.52	, 'elevation' =>	157	),	
	'DRS'=> array('name' => 'Dresden Airport', 'municipality' => 'Dresden', 'lat' =>	51.13	, 'long' =>	13.77	, 'elevation' =>	755	),	
	'FRA'=> array('name' => 'Frankfurt am Main International Airport', 'municipality' => 'Frankfurt-am-Main', 'lat' =>	50.03	, 'long' =>	8.54	, 'elevation' =>	364	),	
	'FMO'=> array('name' => 'M��nster Osnabr��ck Airport', 'municipality' => 'M��nster', 'lat' =>	52.13	, 'long' =>	7.68	, 'elevation' =>	160	),	
	'HAM'=> array('name' => 'Hamburg Airport', 'municipality' => 'Hamburg', 'lat' =>	53.63	, 'long' =>	9.99	, 'elevation' =>	53	),	
	'CGN'=> array('name' => 'Cologne Bonn Airport', 'municipality' => 'Cologne', 'lat' =>	50.87	, 'long' =>	7.14	, 'elevation' =>	302	),	
	'DUS'=> array('name' => 'D��sseldorf International Airport', 'municipality' => 'D��sseldorf', 'lat' =>	51.29	, 'long' =>	6.77	, 'elevation' =>	147	),	
	'MUC'=> array('name' => 'Munich International Airport', 'municipality' => 'Munich', 'lat' =>	48.35	, 'long' =>	11.79	, 'elevation' =>	1487	),	
	'NUE'=> array('name' => 'Nuremberg Airport', 'municipality' => 'Nuremberg', 'lat' =>	49.50	, 'long' =>	11.07	, 'elevation' =>	1046	),	
	'LEJ'=> array('name' => 'Leipzig Halle Airport', 'municipality' => 'Leipzig', 'lat' =>	51.43	, 'long' =>	12.24	, 'elevation' =>	465	),	
	'STR'=> array('name' => 'Stuttgart Airport', 'municipality' => 'Stuttgart', 'lat' =>	48.69	, 'long' =>	9.22	, 'elevation' =>	1276	),	
	'TXL'=> array('name' => 'Berlin-Tegel International Airport', 'municipality' => 'Berlin', 'lat' =>	52.56	, 'long' =>	13.29	, 'elevation' =>	122	),	
	'HAJ'=> array('name' => 'Hannover Airport', 'municipality' => 'Hannover', 'lat' =>	52.46	, 'long' =>	9.69	, 'elevation' =>	183	),	
	'BRE'=> array('name' => 'Bremen Airport', 'municipality' => 'Bremen', 'lat' =>	53.05	, 'long' =>	8.79	, 'elevation' =>	14	),	
	'DTM'=> array('name' => 'Dortmund Airport', 'municipality' => 'Dortmund', 'lat' =>	51.52	, 'long' =>	7.61	, 'elevation' =>	425	),	
	'FKB'=> array('name' => 'Karlsruhe Baden-Baden Airport', 'municipality' => 'Baden-Baden', 'lat' =>	48.78	, 'long' =>	8.08	, 'elevation' =>	408	),	
	'TLL'=> array('name' => 'Lennart Meri Tallinn Airport', 'municipality' => 'Tallinn', 'lat' =>	59.41	, 'long' =>	24.83	, 'elevation' =>	131	),	
	'HEL'=> array('name' => 'Helsinki Vantaa Airport', 'municipality' => 'Helsinki', 'lat' =>	60.32	, 'long' =>	24.96	, 'elevation' =>	179	),	
	'BFS'=> array('name' => 'Belfast International Airport', 'municipality' => 'Belfast', 'lat' =>	54.66	, 'long' =>	-6.22	, 'elevation' =>	268	),	
	'BHD'=> array('name' => 'George Best Belfast City Airport', 'municipality' => 'Belfast', 'lat' =>	54.62	, 'long' =>	-5.87	, 'elevation' =>	15	),	
	'BHX'=> array('name' => 'Birmingham International Airport', 'municipality' => 'Birmingham', 'lat' =>	52.45	, 'long' =>	-1.75	, 'elevation' =>	327	),	
	'MAN'=> array('name' => 'Manchester Airport', 'municipality' => 'Manchester', 'lat' =>	53.35	, 'long' =>	-2.27	, 'elevation' =>	257	),	
	'DSA'=> array('name' => 'Robin Hood Doncaster Sheffield Airport', 'municipality' => 'Doncaster', 'lat' =>	53.48	, 'long' =>	-1.01	, 'elevation' =>	55	),	
	'CWL'=> array('name' => 'Cardiff International Airport', 'municipality' => 'Cardiff', 'lat' =>	51.40	, 'long' =>	-3.34	, 'elevation' =>	220	),	
	'BRS'=> array('name' => 'Bristol International Airport', 'municipality' => 'Bristol', 'lat' =>	51.38	, 'long' =>	-2.72	, 'elevation' =>	622	),	
	'LPL'=> array('name' => 'Liverpool John Lennon Airport', 'municipality' => 'Liverpool', 'lat' =>	53.33	, 'long' =>	-2.85	, 'elevation' =>	80	),	
	'LTN'=> array('name' => 'London Luton Airport', 'municipality' => 'London', 'lat' =>	51.87	, 'long' =>	-0.37	, 'elevation' =>	526	),	
	'BOH'=> array('name' => 'Bournemouth Airport', 'municipality' => 'Bournemouth', 'lat' =>	50.78	, 'long' =>	-1.84	, 'elevation' =>	38	),	
	'SOU'=> array('name' => 'Southampton Airport', 'municipality' => 'Southampton', 'lat' =>	50.95	, 'long' =>	-1.36	, 'elevation' =>	44	),	
	'LGW'=> array('name' => 'London Gatwick Airport', 'municipality' => 'London', 'lat' =>	51.15	, 'long' =>	-0.19	, 'elevation' =>	202	),	
	'LCY'=> array('name' => 'London City Airport', 'municipality' => 'London', 'lat' =>	51.51	, 'long' =>	0.06	, 'elevation' =>	19	),	
	'LHR'=> array('name' => 'London Heathrow Airport', 'municipality' => 'London', 'lat' =>	51.47	, 'long' =>	-0.46	, 'elevation' =>	83	),	
	'LBA'=> array('name' => 'Leeds Bradford Airport', 'municipality' => 'Leeds', 'lat' =>	53.87	, 'long' =>	-1.66	, 'elevation' =>	681	),	
	'NCL'=> array('name' => 'Newcastle Airport', 'municipality' => 'Newcastle', 'lat' =>	55.04	, 'long' =>	-1.69	, 'elevation' =>	266	),	
	'EMA'=> array('name' => 'East Midlands Airport', 'municipality' => 'Nottingham', 'lat' =>	52.83	, 'long' =>	-1.33	, 'elevation' =>	306	),	
	'ABZ'=> array('name' => 'Aberdeen Dyce Airport', 'municipality' => 'Aberdeen', 'lat' =>	57.20	, 'long' =>	-2.20	, 'elevation' =>	215	),	
	'GLA'=> array('name' => 'Glasgow International Airport', 'municipality' => 'Glasgow', 'lat' =>	55.87	, 'long' =>	-4.43	, 'elevation' =>	26	),	
	'EDI'=> array('name' => 'Edinburgh Airport', 'municipality' => 'Edinburgh', 'lat' =>	55.95	, 'long' =>	-3.37	, 'elevation' =>	135	),	
	'NWI'=> array('name' => 'Norwich International Airport', 'municipality' => 'Norwich', 'lat' =>	52.68	, 'long' =>	1.28	, 'elevation' =>	117	),	
	'STN'=> array('name' => 'London Stansted Airport', 'municipality' => 'London', 'lat' =>	51.88	, 'long' =>	0.23	, 'elevation' =>	348	),	
	'EXT'=> array('name' => 'Exeter International Airport', 'municipality' => 'Exeter', 'lat' =>	50.73	, 'long' =>	-3.41	, 'elevation' =>	102	),	
	'LKZ'=> array('name' => 'RAF Lakenheath', 'municipality' => 'Lakenheath', 'lat' =>	52.41	, 'long' =>	0.56	, 'elevation' =>	32	),	
	'MHZ'=> array('name' => 'RAF Mildenhall', 'municipality' => 'Mildenhall', 'lat' =>	52.36	, 'long' =>	0.49	, 'elevation' =>	33	),	
	'FFD'=> array('name' => 'RAF Fairford', 'municipality' => 'Fairford', 'lat' =>	51.68	, 'long' =>	-1.79	, 'elevation' =>	286	),	
	'BZZ'=> array('name' => 'RAF Brize Norton', 'municipality' => 'Brize Norton', 'lat' =>	51.75	, 'long' =>	-1.58	, 'elevation' =>	288	),	
	'AMS'=> array('name' => 'Amsterdam Airport Schiphol', 'municipality' => 'Amsterdam', 'lat' =>	52.31	, 'long' =>	4.76	, 'elevation' =>	-11	),	
	'MST'=> array('name' => 'Maastricht Aachen Airport', 'municipality' => 'Maastricht', 'lat' =>	50.91	, 'long' =>	5.77	, 'elevation' =>	375	),	
	'EIN'=> array('name' => 'Eindhoven Airport', 'municipality' => 'Eindhoven', 'lat' =>	51.45	, 'long' =>	5.37	, 'elevation' =>	74	),	
	'ORK'=> array('name' => 'Cork Airport', 'municipality' => 'Cork', 'lat' =>	51.84	, 'long' =>	-8.49	, 'elevation' =>	502	),	
	'DUB'=> array('name' => 'Dublin Airport', 'municipality' => 'Dublin', 'lat' =>	53.42	, 'long' =>	-6.27	, 'elevation' =>	242	),	
	'SNN'=> array('name' => 'Shannon Airport', 'municipality' => 'Limerick', 'lat' =>	52.70	, 'long' =>	-8.92	, 'elevation' =>	46	),	
	'BLL'=> array('name' => 'Billund Airport', 'municipality' => 'Billund', 'lat' =>	55.74	, 'long' =>	9.15	, 'elevation' =>	247	),	
	'CPH'=> array('name' => 'Copenhagen Kastrup Airport', 'municipality' => 'Copenhagen', 'lat' =>	55.62	, 'long' =>	12.66	, 'elevation' =>	17	),	
	'AAL'=> array('name' => 'Aalborg Airport', 'municipality' => 'Aalborg', 'lat' =>	57.09	, 'long' =>	9.85	, 'elevation' =>	10	),	
	'LUX'=> array('name' => 'Luxembourg-Findel International Airport', 'municipality' => 'Luxembourg', 'lat' =>	49.63	, 'long' =>	6.21	, 'elevation' =>	1234	),	
	'BOO'=> array('name' => 'Bod�� Airport', 'municipality' => 'Bod��', 'lat' =>	67.27	, 'long' =>	14.37	, 'elevation' =>	42	),	
	'BGO'=> array('name' => 'Bergen Airport, Flesland', 'municipality' => 'Bergen', 'lat' =>	60.29	, 'long' =>	5.22	, 'elevation' =>	170	),	
	'OSL'=> array('name' => 'Oslo Gardermoen Airport', 'municipality' => 'Oslo', 'lat' =>	60.19	, 'long' =>	11.10	, 'elevation' =>	681	),	
	'TOS'=> array('name' => 'Troms�� Airport', 'municipality' => 'Troms��', 'lat' =>	69.68	, 'long' =>	18.92	, 'elevation' =>	31	),	
	'TRD'=> array('name' => 'Trondheim Airport, V��rnes', 'municipality' => 'Trondheim', 'lat' =>	63.46	, 'long' =>	10.92	, 'elevation' =>	56	),	
	'SVG'=> array('name' => 'Stavanger Airport, Sola', 'municipality' => 'Stavanger', 'lat' =>	58.88	, 'long' =>	5.64	, 'elevation' =>	29	),	
	'GDN'=> array('name' => 'Gda��sk Lech Wa����sa Airport', 'municipality' => 'Gda��sk', 'lat' =>	54.38	, 'long' =>	18.47	, 'elevation' =>	489	),	
	'KRK'=> array('name' => 'John Paul II International Airport Krak��w-Balice Airport', 'municipality' => 'Krak��w', 'lat' =>	50.08	, 'long' =>	19.78	, 'elevation' =>	791	),	
	'KTW'=> array('name' => 'Katowice International Airport', 'municipality' => 'Katowice', 'lat' =>	50.47	, 'long' =>	19.08	, 'elevation' =>	995	),	
	'WMI'=> array('name' => 'Modlin Airport', 'municipality' => 'Warsaw', 'lat' =>	52.45	, 'long' =>	20.65	, 'elevation' =>	341	),	
	'POZ'=> array('name' => 'Pozna��-��awica Airport', 'municipality' => 'Pozna��', 'lat' =>	52.42	, 'long' =>	16.83	, 'elevation' =>	308	),	
	'WAW'=> array('name' => 'Warsaw Chopin Airport', 'municipality' => 'Warsaw', 'lat' =>	52.17	, 'long' =>	20.97	, 'elevation' =>	362	),	
	'WRO'=> array('name' => 'Copernicus Wroc��aw Airport', 'municipality' => 'Wroc��aw', 'lat' =>	51.10	, 'long' =>	16.89	, 'elevation' =>	404	),	
	'GOT'=> array('name' => 'Gothenburg-Landvetter Airport', 'municipality' => 'Gothenburg', 'lat' =>	57.66	, 'long' =>	12.28	, 'elevation' =>	506	),	
	'MMX'=> array('name' => 'Malm�� Sturup Airport', 'municipality' => 'Malm��', 'lat' =>	55.54	, 'long' =>	13.38	, 'elevation' =>	236	),	
	'LLA'=> array('name' => 'Lule�� Airport', 'municipality' => 'Lule��', 'lat' =>	65.54	, 'long' =>	22.12	, 'elevation' =>	65	),	
	'ARN'=> array('name' => 'Stockholm-Arlanda Airport', 'municipality' => 'Stockholm', 'lat' =>	59.65	, 'long' =>	17.92	, 'elevation' =>	137	),	
	'RMS'=> array('name' => 'Ramstein Air Base', 'municipality' => 'Ramstein', 'lat' =>	49.44	, 'long' =>	7.60	, 'elevation' =>	776	),	
	'RIX'=> array('name' => 'Riga International Airport', 'municipality' => 'Riga', 'lat' =>	56.92	, 'long' =>	23.97	, 'elevation' =>	36	),	
	'VNO'=> array('name' => 'Vilnius International Airport', 'municipality' => 'Vilnius', 'lat' =>	54.63	, 'long' =>	25.29	, 'elevation' =>	646	),	
	'CPT'=> array('name' => 'Cape Town International Airport', 'municipality' => 'Cape Town', 'lat' =>	-33.96	, 'long' =>	18.60	, 'elevation' =>	151	),	
	'GRJ'=> array('name' => 'George Airport', 'municipality' => 'George', 'lat' =>	-34.01	, 'long' =>	22.38	, 'elevation' =>	648	),	
	'JNB'=> array('name' => 'OR Tambo International Airport', 'municipality' => 'Johannesburg', 'lat' =>	-26.14	, 'long' =>	28.25	, 'elevation' =>	5558	),	
	'DUR'=> array('name' => 'King Shaka International Airport', 'municipality' => 'Durban', 'lat' =>	-29.61	, 'long' =>	31.12	, 'elevation' =>	295	),	
	'LPA'=> array('name' => 'Gran Canaria Airport', 'municipality' => 'Gran Canaria Island', 'lat' =>	27.93	, 'long' =>	-15.39	, 'elevation' =>	78	),	
	'TFS'=> array('name' => 'Tenerife South Airport', 'municipality' => 'Tenerife Island', 'lat' =>	28.04	, 'long' =>	-16.57	, 'elevation' =>	209	),	
	'TFN'=> array('name' => 'Tenerife Norte Airport', 'municipality' => 'Tenerife Island', 'lat' =>	28.48	, 'long' =>	-16.34	, 'elevation' =>	2076	),	
	'CMN'=> array('name' => 'Mohammed V International Airport', 'municipality' => 'Casablanca', 'lat' =>	33.37	, 'long' =>	-7.59	, 'elevation' =>	656	),	
	'DKR'=> array('name' => 'L��opold S��dar Senghor International Airport', 'municipality' => 'Dakar', 'lat' =>	14.74	, 'long' =>	-17.49	, 'elevation' =>	85	),	
	'ADD'=> array('name' => 'Addis Ababa Bole International Airport', 'municipality' => 'Addis Ababa', 'lat' =>	8.98	, 'long' =>	38.80	, 'elevation' =>	7630	),	
	'CAI'=> array('name' => 'Cairo International Airport', 'municipality' => 'Cairo', 'lat' =>	30.12	, 'long' =>	31.41	, 'elevation' =>	382	),	
	'HRG'=> array('name' => 'Hurghada International Airport', 'municipality' => 'Hurghada', 'lat' =>	27.18	, 'long' =>	33.80	, 'elevation' =>	52	),	
	'NBO'=> array('name' => 'Jomo Kenyatta International Airport', 'municipality' => 'Nairobi', 'lat' =>	-1.32	, 'long' =>	36.93	, 'elevation' =>	5330	),	
	'MBA'=> array('name' => 'Mombasa Moi International Airport', 'municipality' => 'Mombasa', 'lat' =>	-4.03	, 'long' =>	39.59	, 'elevation' =>	200	),	
	'TIP'=> array('name' => 'Tripoli International Airport', 'municipality' => 'Tripoli', 'lat' =>	32.66	, 'long' =>	13.16	, 'elevation' =>	263	),	
	'JUB'=> array('name' => 'Juba International Airport', 'municipality' => 'Juba', 'lat' =>	4.87	, 'long' =>	31.60	, 'elevation' =>	1513	),	
	'KRT'=> array('name' => 'Khartoum International Airport', 'municipality' => 'Khartoum', 'lat' =>	15.59	, 'long' =>	32.55	, 'elevation' =>	1265	),	
	'KNO'=> array('name' => 'Medan-Kuala Namu International Airport', 'municipality' => '', 'lat' =>	3.64	, 'long' =>	98.89	, 'elevation' => 'UNK'		),	
	'ABQ'=> array('name' => 'Albuquerque International Sunport Airport', 'municipality' => 'Albuquerque', 'lat' =>	35.04	, 'long' =>	-106.61	, 'elevation' =>	5355	),	
	'ADW'=> array('name' => 'Andrews Air Force Base', 'municipality' => 'Camp Springs', 'lat' =>	38.81	, 'long' =>	-76.87	, 'elevation' =>	280	),	
	'AFW'=> array('name' => 'Fort Worth Alliance Airport', 'municipality' => 'Fort Worth', 'lat' =>	32.99	, 'long' =>	-97.32	, 'elevation' =>	722	),	
	'AGS'=> array('name' => 'Augusta Regional At Bush Field', 'municipality' => 'Augusta', 'lat' =>	33.37	, 'long' =>	-81.96	, 'elevation' =>	144	),	
	'AMA'=> array('name' => 'Rick Husband Amarillo International Airport', 'municipality' => 'Amarillo', 'lat' =>	35.22	, 'long' =>	-101.71	, 'elevation' =>	3607	),	
	'ATL'=> array('name' => 'Hartsfield Jackson Atlanta International Airport', 'municipality' => 'Atlanta', 'lat' =>	33.64	, 'long' =>	-84.43	, 'elevation' =>	1026	),	
	'AUS'=> array('name' => 'Austin Bergstrom International Airport', 'municipality' => 'Austin', 'lat' =>	30.19	, 'long' =>	-97.67	, 'elevation' =>	542	),	
	'AVL'=> array('name' => 'Asheville Regional Airport', 'municipality' => 'Asheville', 'lat' =>	35.44	, 'long' =>	-82.54	, 'elevation' =>	2165	),	
	'BAB'=> array('name' => 'Beale Air Force Base', 'municipality' => 'Marysville', 'lat' =>	39.14	, 'long' =>	-121.44	, 'elevation' =>	113	),	
	'BAD'=> array('name' => 'Barksdale Air Force Base', 'municipality' => 'Bossier City', 'lat' =>	32.50	, 'long' =>	-93.66	, 'elevation' =>	166	),	
	'BDL'=> array('name' => 'Bradley International Airport', 'municipality' => 'Hartford', 'lat' =>	41.94	, 'long' =>	-72.68	, 'elevation' =>	173	),	
	'BFI'=> array('name' => 'Boeing Field King County International Airport', 'municipality' => 'Seattle', 'lat' =>	47.53	, 'long' =>	-122.30	, 'elevation' =>	21	),	
	'BGR'=> array('name' => 'Bangor International Airport', 'municipality' => 'Bangor', 'lat' =>	44.81	, 'long' =>	-68.83	, 'elevation' =>	192	),	
	'BHM'=> array('name' => 'Birmingham-Shuttlesworth International Airport', 'municipality' => 'Birmingham', 'lat' =>	33.56	, 'long' =>	-86.75	, 'elevation' =>	650	),	
	'BIL'=> array('name' => 'Billings Logan International Airport', 'municipality' => 'Billings', 'lat' =>	45.81	, 'long' =>	-108.54	, 'elevation' =>	3652	),	
	'BLV'=> array('name' => 'Scott AFB/Midamerica Airport', 'municipality' => 'Belleville', 'lat' =>	38.55	, 'long' =>	-89.84	, 'elevation' =>	459	),	
	'BMI'=> array('name' => 'Central Illinois Regional Airport at Bloomington-Normal', 'municipality' => 'Bloomington/Normal', 'lat' =>	40.48	, 'long' =>	-88.92	, 'elevation' =>	871	),	
	'BNA'=> array('name' => 'Nashville International Airport', 'municipality' => 'Nashville', 'lat' =>	36.12	, 'long' =>	-86.68	, 'elevation' =>	599	),	
	'BOI'=> array('name' => 'Boise Air Terminal/Gowen field', 'municipality' => 'Boise', 'lat' =>	43.56	, 'long' =>	-116.22	, 'elevation' =>	2871	),	
	'BOS'=> array('name' => 'General Edward Lawrence Logan International Airport', 'municipality' => 'Boston', 'lat' =>	42.36	, 'long' =>	-71.01	, 'elevation' =>	20	),	
	'BTR'=> array('name' => 'Baton Rouge Metropolitan, Ryan Field', 'municipality' => 'Baton Rouge', 'lat' =>	30.53	, 'long' =>	-91.15	, 'elevation' =>	70	),	
	'BUF'=> array('name' => 'Buffalo Niagara International Airport', 'municipality' => 'Buffalo', 'lat' =>	42.94	, 'long' =>	-78.73	, 'elevation' =>	728	),	
	'BWI'=> array('name' => 'Baltimore/Washington International Thurgood Marshall Airport', 'municipality' => 'Baltimore', 'lat' =>	39.18	, 'long' =>	-76.67	, 'elevation' =>	146	),	
	'CAE'=> array('name' => 'Columbia Metropolitan Airport', 'municipality' => 'Columbia', 'lat' =>	33.94	, 'long' =>	-81.12	, 'elevation' =>	236	),	
	'CBM'=> array('name' => 'Columbus Air Force Base', 'municipality' => 'Columbus', 'lat' =>	33.64	, 'long' =>	-88.44	, 'elevation' =>	219	),	
	'CHA'=> array('name' => 'Lovell Field', 'municipality' => 'Chattanooga', 'lat' =>	35.04	, 'long' =>	-85.20	, 'elevation' =>	683	),	
	'CHS'=> array('name' => 'Charleston Air Force Base-International Airport', 'municipality' => 'Charleston', 'lat' =>	32.90	, 'long' =>	-80.04	, 'elevation' =>	46	),	
	'CID'=> array('name' => 'The Eastern Iowa Airport', 'municipality' => 'Cedar Rapids', 'lat' =>	41.88	, 'long' =>	-91.71	, 'elevation' =>	869	),	
	'CLE'=> array('name' => 'Cleveland Hopkins International Airport', 'municipality' => 'Cleveland', 'lat' =>	41.41	, 'long' =>	-81.85	, 'elevation' =>	791	),	
	'CLT'=> array('name' => 'Charlotte Douglas International Airport', 'municipality' => 'Charlotte', 'lat' =>	35.21	, 'long' =>	-80.94	, 'elevation' =>	748	),	
	'CMH'=> array('name' => 'Port Columbus International Airport', 'municipality' => 'Columbus', 'lat' =>	40.00	, 'long' =>	-82.89	, 'elevation' =>	815	),	
	'COS'=> array('name' => 'City of Colorado Springs Municipal Airport', 'municipality' => 'Colorado Springs', 'lat' =>	38.81	, 'long' =>	-104.70	, 'elevation' =>	6187	),	
	'CPR'=> array('name' => 'Casper-Natrona County International Airport', 'municipality' => 'Casper', 'lat' =>	42.91	, 'long' =>	-106.46	, 'elevation' =>	5350	),	
	'CRP'=> array('name' => 'Corpus Christi International Airport', 'municipality' => 'Corpus Christi', 'lat' =>	27.77	, 'long' =>	-97.50	, 'elevation' =>	44	),	
	'CRW'=> array('name' => 'Yeager Airport', 'municipality' => 'Charleston', 'lat' =>	38.37	, 'long' =>	-81.59	, 'elevation' =>	981	),	
	'CVG'=> array('name' => 'Cincinnati Northern Kentucky International Airport', 'municipality' => 'Cincinnati', 'lat' =>	39.05	, 'long' =>	-84.67	, 'elevation' =>	896	),	
	'CVS'=> array('name' => 'Cannon Air Force Base', 'municipality' => 'Clovis', 'lat' =>	34.38	, 'long' =>	-103.32	, 'elevation' =>	4295	),	
	'DAL'=> array('name' => 'Dallas Love Field', 'municipality' => 'Dallas', 'lat' =>	32.85	, 'long' =>	-96.85	, 'elevation' =>	487	),	
	'DAY'=> array('name' => 'James M Cox Dayton International Airport', 'municipality' => 'Dayton', 'lat' =>	39.90	, 'long' =>	-84.22	, 'elevation' =>	1009	),	
	'DBQ'=> array('name' => 'Dubuque Regional Airport', 'municipality' => 'Dubuque', 'lat' =>	42.40	, 'long' =>	-90.71	, 'elevation' =>	1077	),	
	'DCA'=> array('name' => 'Ronald Reagan Washington National Airport', 'municipality' => 'Washington', 'lat' =>	38.85	, 'long' =>	-77.04	, 'elevation' =>	15	),	
	'DEN'=> array('name' => 'Denver International Airport', 'municipality' => 'Denver', 'lat' =>	39.86	, 'long' =>	-104.67	, 'elevation' =>	5431	),	
	'DFW'=> array('name' => 'Dallas Fort Worth International Airport', 'municipality' => 'Dallas-Fort Worth', 'lat' =>	32.90	, 'long' =>	-97.04	, 'elevation' =>	607	),	
	'DLF'=> array('name' => 'Laughlin Air Force Base', 'municipality' => 'Del Rio', 'lat' =>	29.36	, 'long' =>	-100.78	, 'elevation' =>	1082	),	
	'DLH'=> array('name' => 'Duluth International Airport', 'municipality' => 'Duluth', 'lat' =>	46.84	, 'long' =>	-92.19	, 'elevation' =>	1428	),	
	'DOV'=> array('name' => 'Dover Air Force Base', 'municipality' => 'Dover', 'lat' =>	39.13	, 'long' =>	-75.47	, 'elevation' =>	24	),	
	'DSM'=> array('name' => 'Des Moines International Airport', 'municipality' => 'Des Moines', 'lat' =>	41.53	, 'long' =>	-93.66	, 'elevation' =>	958	),	
	'DTW'=> array('name' => 'Detroit Metropolitan Wayne County Airport', 'municipality' => 'Detroit', 'lat' =>	42.21	, 'long' =>	-83.35	, 'elevation' =>	645	),	
	'DYS'=> array('name' => 'Dyess Air Force Base', 'municipality' => 'Abilene', 'lat' =>	32.42	, 'long' =>	-99.85	, 'elevation' =>	1789	),	
	'END'=> array('name' => 'Vance Air Force Base', 'municipality' => 'Enid', 'lat' =>	36.34	, 'long' =>	-97.92	, 'elevation' =>	1307	),	
	'ERI'=> array('name' => 'Erie International Tom Ridge Field', 'municipality' => 'Erie', 'lat' =>	42.08	, 'long' =>	-80.17	, 'elevation' =>	732	),	
	'EWR'=> array('name' => 'Newark Liberty International Airport', 'municipality' => 'Newark', 'lat' =>	40.69	, 'long' =>	-74.17	, 'elevation' =>	18	),	
	'FFO'=> array('name' => 'Wright-Patterson Air Force Base', 'municipality' => 'Dayton', 'lat' =>	39.83	, 'long' =>	-84.05	, 'elevation' =>	823	),	
	'FLL'=> array('name' => 'Fort Lauderdale Hollywood International Airport', 'municipality' => 'Fort Lauderdale', 'lat' =>	26.07	, 'long' =>	-80.15	, 'elevation' =>	9	),	
	'FSM'=> array('name' => 'Fort Smith Regional Airport', 'municipality' => 'Fort Smith', 'lat' =>	35.34	, 'long' =>	-94.37	, 'elevation' =>	469	),	
	'FTW'=> array('name' => 'Fort Worth Meacham International Airport', 'municipality' => 'Fort Worth', 'lat' =>	32.82	, 'long' =>	-97.36	, 'elevation' =>	710	),	
	'FWA'=> array('name' => 'Fort Wayne International Airport', 'municipality' => 'Fort Wayne', 'lat' =>	40.98	, 'long' =>	-85.20	, 'elevation' =>	814	),	
	'GEG'=> array('name' => 'Spokane International Airport', 'municipality' => 'Spokane', 'lat' =>	47.62	, 'long' =>	-117.53	, 'elevation' =>	2376	),	
	'GPT'=> array('name' => 'Gulfport Biloxi International Airport', 'municipality' => 'Gulfport', 'lat' =>	30.41	, 'long' =>	-89.07	, 'elevation' =>	28	),	
	'GRB'=> array('name' => 'Austin Straubel International Airport', 'municipality' => 'Green Bay', 'lat' =>	44.49	, 'long' =>	-88.13	, 'elevation' =>	695	),	
	'GSB'=> array('name' => 'Seymour Johnson Air Force Base', 'municipality' => 'Goldsboro', 'lat' =>	35.34	, 'long' =>	-77.96	, 'elevation' =>	109	),	
	'GSO'=> array('name' => 'Piedmont Triad International Airport', 'municipality' => 'Greensboro', 'lat' =>	36.10	, 'long' =>	-79.94	, 'elevation' =>	925	),	
	'GSP'=> array('name' => 'Greenville Spartanburg International Airport', 'municipality' => 'Greenville', 'lat' =>	34.90	, 'long' =>	-82.22	, 'elevation' =>	964	),	
	'GUS'=> array('name' => 'Grissom Air Reserve Base', 'municipality' => 'Peru', 'lat' =>	40.65	, 'long' =>	-86.15	, 'elevation' =>	812	),	
	'HIB'=> array('name' => 'Range Regional Airport', 'municipality' => 'Hibbing', 'lat' =>	47.39	, 'long' =>	-92.84	, 'elevation' =>	1354	),	
	'HMN'=> array('name' => 'Holloman Air Force Base', 'municipality' => 'Alamogordo', 'lat' =>	32.85	, 'long' =>	-106.11	, 'elevation' =>	4093	),	
	'HOU'=> array('name' => 'William P Hobby Airport', 'municipality' => 'Houston', 'lat' =>	29.65	, 'long' =>	-95.28	, 'elevation' =>	46	),	
	'HSV'=> array('name' => 'Huntsville International Carl T Jones Field', 'municipality' => 'Huntsville', 'lat' =>	34.64	, 'long' =>	-86.78	, 'elevation' =>	629	),	
	'HTS'=> array('name' => 'Tri-State/Milton J. Ferguson Field', 'municipality' => 'Huntington', 'lat' =>	38.37	, 'long' =>	-82.56	, 'elevation' =>	828	),	
	'IAD'=> array('name' => 'Washington Dulles International Airport', 'municipality' => 'Washington', 'lat' =>	38.94	, 'long' =>	-77.46	, 'elevation' =>	312	),	
	'IAH'=> array('name' => 'George Bush Intercontinental Houston Airport', 'municipality' => 'Houston', 'lat' =>	29.98	, 'long' =>	-95.34	, 'elevation' =>	97	),	
	'ICT'=> array('name' => 'Wichita Mid Continent Airport', 'municipality' => 'Wichita', 'lat' =>	37.65	, 'long' =>	-97.43	, 'elevation' =>	1333	),	
	'IND'=> array('name' => 'Indianapolis International Airport', 'municipality' => 'Indianapolis', 'lat' =>	39.72	, 'long' =>	-86.29	, 'elevation' =>	797	),	
	'JAN'=> array('name' => 'Jackson-Medgar Wiley Evers International Airport', 'municipality' => 'Jackson', 'lat' =>	32.31	, 'long' =>	-90.08	, 'elevation' =>	346	),	
	'JAX'=> array('name' => 'Jacksonville International Airport', 'municipality' => 'Jacksonville', 'lat' =>	30.49	, 'long' =>	-81.69	, 'elevation' =>	30	),	
	'JFK'=> array('name' => 'John F Kennedy International Airport', 'municipality' => 'New York', 'lat' =>	40.64	, 'long' =>	-73.78	, 'elevation' =>	13	),	
	'JLN'=> array('name' => 'Joplin Regional Airport', 'municipality' => 'Joplin', 'lat' =>	37.15	, 'long' =>	-94.50	, 'elevation' =>	981	),	
	'LAS'=> array('name' => 'McCarran International Airport', 'municipality' => 'Las Vegas', 'lat' =>	36.08	, 'long' =>	-115.15	, 'elevation' =>	2181	),	
	'LAX'=> array('name' => 'Los Angeles International Airport', 'municipality' => 'Los Angeles', 'lat' =>	33.94	, 'long' =>	-118.41	, 'elevation' =>	125	),	
	'LBB'=> array('name' => 'Lubbock Preston Smith International Airport', 'municipality' => 'Lubbock', 'lat' =>	33.66	, 'long' =>	-101.82	, 'elevation' =>	3282	),	
	'LCK'=> array('name' => 'Rickenbacker International Airport', 'municipality' => 'Columbus', 'lat' =>	39.81	, 'long' =>	-82.93	, 'elevation' =>	744	),	
	'LEX'=> array('name' => 'Blue Grass Airport', 'municipality' => 'Lexington', 'lat' =>	38.04	, 'long' =>	-84.61	, 'elevation' =>	979	),	
	'LFI'=> array('name' => 'Langley Air Force Base', 'municipality' => 'Hampton', 'lat' =>	37.08	, 'long' =>	-76.36	, 'elevation' =>	11	),	
	'LFT'=> array('name' => 'Lafayette Regional Airport', 'municipality' => 'Lafayette', 'lat' =>	30.21	, 'long' =>	-91.99	, 'elevation' =>	42	),	
	'LGA'=> array('name' => 'La Guardia Airport', 'municipality' => 'New York', 'lat' =>	40.78	, 'long' =>	-73.87	, 'elevation' =>	21	),	
	'LIT'=> array('name' => 'Bill & Hillary Clinton National Airport/Adams Field', 'municipality' => 'Little Rock', 'lat' =>	34.73	, 'long' =>	-92.22	, 'elevation' =>	262	),	
	'LTS'=> array('name' => 'Altus Air Force Base', 'municipality' => 'Altus', 'lat' =>	34.67	, 'long' =>	-99.27	, 'elevation' =>	1382	),	
	'LUF'=> array('name' => 'Luke Air Force Base', 'municipality' => 'Glendale', 'lat' =>	33.53	, 'long' =>	-112.38	, 'elevation' =>	1085	),	
	'MBS'=> array('name' => 'MBS International Airport', 'municipality' => 'Saginaw', 'lat' =>	43.53	, 'long' =>	-84.08	, 'elevation' =>	668	),	
	'MCF'=> array('name' => 'Mac Dill Air Force Base', 'municipality' => 'Tampa', 'lat' =>	27.85	, 'long' =>	-82.52	, 'elevation' =>	14	),	
	'MCI'=> array('name' => 'Kansas City International Airport', 'municipality' => 'Kansas City', 'lat' =>	39.30	, 'long' =>	-94.71	, 'elevation' =>	1026	),	
	'MCO'=> array('name' => 'Orlando International Airport', 'municipality' => 'Orlando', 'lat' =>	28.43	, 'long' =>	-81.31	, 'elevation' =>	96	),	
	'MDW'=> array('name' => 'Chicago Midway International Airport', 'municipality' => 'Chicago', 'lat' =>	41.79	, 'long' =>	-87.75	, 'elevation' =>	620	),	
	'MEM'=> array('name' => 'Memphis International Airport', 'municipality' => 'Memphis', 'lat' =>	35.04	, 'long' =>	-89.98	, 'elevation' =>	341	),	
	'MGE'=> array('name' => 'Dobbins Air Reserve Base', 'municipality' => 'Marietta', 'lat' =>	33.92	, 'long' =>	-84.52	, 'elevation' =>	1068	),	
	'MGM'=> array('name' => 'Montgomery Regional (Dannelly Field) Airport', 'municipality' => 'Montgomery', 'lat' =>	32.30	, 'long' =>	-86.39	, 'elevation' =>	221	),	
	'MHT'=> array('name' => 'Manchester Airport', 'municipality' => 'Manchester', 'lat' =>	42.93	, 'long' =>	-71.44	, 'elevation' =>	266	),	
	'MIA'=> array('name' => 'Miami International Airport', 'municipality' => 'Miami', 'lat' =>	25.79	, 'long' =>	-80.29	, 'elevation' =>	8	),	
	'MKE'=> array('name' => 'General Mitchell International Airport', 'municipality' => 'Milwaukee', 'lat' =>	42.95	, 'long' =>	-87.90	, 'elevation' =>	723	),	
	'MLI'=> array('name' => 'Quad City International Airport', 'municipality' => 'Moline', 'lat' =>	41.45	, 'long' =>	-90.51	, 'elevation' =>	590	),	
	'MLU'=> array('name' => 'Monroe Regional Airport', 'municipality' => 'Monroe', 'lat' =>	32.51	, 'long' =>	-92.04	, 'elevation' =>	79	),	
	'MOB'=> array('name' => 'Mobile Regional Airport', 'municipality' => 'Mobile', 'lat' =>	30.69	, 'long' =>	-88.24	, 'elevation' =>	219	),	
	'MSN'=> array('name' => 'Dane County Regional Truax Field', 'municipality' => 'Madison', 'lat' =>	43.14	, 'long' =>	-89.34	, 'elevation' =>	887	),	
	'MSP'=> array('name' => 'Minneapolis-St Paul International/Wold-Chamberlain Airport', 'municipality' => 'Minneapolis', 'lat' =>	44.88	, 'long' =>	-93.22	, 'elevation' =>	841	),	
	'MSY'=> array('name' => 'Louis Armstrong New Orleans International Airport', 'municipality' => 'New Orleans', 'lat' =>	29.99	, 'long' =>	-90.26	, 'elevation' =>	4	),	
	'OAK'=> array('name' => 'Metropolitan Oakland International Airport', 'municipality' => 'Oakland', 'lat' =>	37.72	, 'long' =>	-122.22	, 'elevation' =>	9	),	
	'OKC'=> array('name' => 'Will Rogers World Airport', 'municipality' => 'Oklahoma City', 'lat' =>	35.39	, 'long' =>	-97.60	, 'elevation' =>	1295	),	
	'ONT'=> array('name' => 'Ontario International Airport', 'municipality' => 'Ontario', 'lat' =>	34.06	, 'long' =>	-117.60	, 'elevation' =>	944	),	
	'ORD'=> array('name' => 'Chicago O Hare International Airport', 'municipality' => 'Chicago', 'lat' =>	41.98	, 'long' =>	-87.90	, 'elevation' =>	672	),	
	'ORF'=> array('name' => 'Norfolk International Airport', 'municipality' => 'Norfolk', 'lat' =>	36.89	, 'long' =>	-76.20	, 'elevation' =>	26	),	
	'PAM'=> array('name' => 'Tyndall Air Force Base', 'municipality' => 'Panama City', 'lat' =>	30.07	, 'long' =>	-85.58	, 'elevation' =>	17	),	
	'PBI'=> array('name' => 'Palm Beach International Airport', 'municipality' => 'West Palm Beach', 'lat' =>	26.68	, 'long' =>	-80.10	, 'elevation' =>	19	),	
	'PDX'=> array('name' => 'Portland International Airport', 'municipality' => 'Portland', 'lat' =>	45.59	, 'long' =>	-122.60	, 'elevation' =>	31	),	
	'PHF'=> array('name' => 'Newport News Williamsburg International Airport', 'municipality' => 'Newport News', 'lat' =>	37.13	, 'long' =>	-76.49	, 'elevation' =>	42	),	
	'PHL'=> array('name' => 'Philadelphia International Airport', 'municipality' => 'Philadelphia', 'lat' =>	39.87	, 'long' =>	-75.24	, 'elevation' =>	36	),	
	'PHX'=> array('name' => 'Phoenix Sky Harbor International Airport', 'municipality' => 'Phoenix', 'lat' =>	33.43	, 'long' =>	-112.01	, 'elevation' =>	1135	),	
	'PIA'=> array('name' => 'General Wayne A. Downing Peoria International Airport', 'municipality' => 'Peoria', 'lat' =>	40.66	, 'long' =>	-89.69	, 'elevation' =>	660	),	
	'PIT'=> array('name' => 'Pittsburgh International Airport', 'municipality' => 'Pittsburgh', 'lat' =>	40.49	, 'long' =>	-80.23	, 'elevation' =>	1203	),	
	'PWM'=> array('name' => 'Portland International Jetport Airport', 'municipality' => 'Portland', 'lat' =>	43.65	, 'long' =>	-70.31	, 'elevation' =>	76	),	
	'RDU'=> array('name' => 'Raleigh Durham International Airport', 'municipality' => 'Raleigh/Durham', 'lat' =>	35.88	, 'long' =>	-78.79	, 'elevation' =>	435	),	
	'RFD'=> array('name' => 'Chicago Rockford International Airport', 'municipality' => 'Chicago/Rockford', 'lat' =>	42.20	, 'long' =>	-89.10	, 'elevation' =>	742	),	
	'RIC'=> array('name' => 'Richmond International Airport', 'municipality' => 'Richmond', 'lat' =>	37.51	, 'long' =>	-77.32	, 'elevation' =>	167	),	
	'RND'=> array('name' => 'Randolph Air Force Base', 'municipality' => 'Universal City', 'lat' =>	29.53	, 'long' =>	-98.28	, 'elevation' =>	761	),	
	'RNO'=> array('name' => 'Reno Tahoe International Airport', 'municipality' => 'Reno', 'lat' =>	39.50	, 'long' =>	-119.77	, 'elevation' =>	4415	),	
	'ROA'=> array('name' => 'Roanoke���Blacksburg Regional Airport', 'municipality' => 'Roanoke', 'lat' =>	37.33	, 'long' =>	-79.98	, 'elevation' =>	1175	),	
	'ROC'=> array('name' => 'Greater Rochester International Airport', 'municipality' => 'Rochester', 'lat' =>	43.12	, 'long' =>	-77.67	, 'elevation' =>	559	),	
	'RST'=> array('name' => 'Rochester International Airport', 'municipality' => 'Rochester', 'lat' =>	43.91	, 'long' =>	-92.50	, 'elevation' =>	1317	),	
	'RSW'=> array('name' => 'Southwest Florida International Airport', 'municipality' => 'Fort Myers', 'lat' =>	26.54	, 'long' =>	-81.76	, 'elevation' =>	30	),	
	'SAN'=> array('name' => 'San Diego International Airport', 'municipality' => 'San Diego', 'lat' =>	32.73	, 'long' =>	-117.19	, 'elevation' =>	17	),	
	'SAT'=> array('name' => 'San Antonio International Airport', 'municipality' => 'San Antonio', 'lat' =>	29.53	, 'long' =>	-98.47	, 'elevation' =>	809	),	
	'SAV'=> array('name' => 'Savannah Hilton Head International Airport', 'municipality' => 'Savannah', 'lat' =>	32.13	, 'long' =>	-81.20	, 'elevation' =>	50	),	
	'SBN'=> array('name' => 'South Bend Regional Airport', 'municipality' => 'South Bend', 'lat' =>	41.71	, 'long' =>	-86.32	, 'elevation' =>	799	),	
	'SDF'=> array('name' => 'Louisville International Standiford Field', 'municipality' => 'Louisville', 'lat' =>	38.17	, 'long' =>	-85.74	, 'elevation' =>	501	),	
	'SEA'=> array('name' => 'Seattle Tacoma International Airport', 'municipality' => 'Seattle', 'lat' =>	47.45	, 'long' =>	-122.31	, 'elevation' =>	433	),	
	'SFB'=> array('name' => 'Orlando Sanford International Airport', 'municipality' => 'Orlando', 'lat' =>	28.78	, 'long' =>	-81.24	, 'elevation' =>	55	),	
	'SFO'=> array('name' => 'San Francisco International Airport', 'municipality' => 'San Francisco', 'lat' =>	37.62	, 'long' =>	-122.38	, 'elevation' =>	13	),	
	'SGF'=> array('name' => 'Springfield Branson National Airport', 'municipality' => 'Springfield', 'lat' =>	37.25	, 'long' =>	-93.39	, 'elevation' =>	1268	),	
	'SHV'=> array('name' => 'Shreveport Regional Airport', 'municipality' => 'Shreveport', 'lat' =>	32.45	, 'long' =>	-93.83	, 'elevation' =>	258	),	
	'SJC'=> array('name' => 'Norman Y. Mineta San Jose International Airport', 'municipality' => 'San Jose', 'lat' =>	37.36	, 'long' =>	-121.93	, 'elevation' =>	62	),	
	'SKA'=> array('name' => 'Fairchild Air Force Base', 'municipality' => 'Spokane', 'lat' =>	47.62	, 'long' =>	-117.66	, 'elevation' =>	2461	),	
	'SLC'=> array('name' => 'Salt Lake City International Airport', 'municipality' => 'Salt Lake City', 'lat' =>	40.79	, 'long' =>	-111.98	, 'elevation' =>	4227	),	
	'SMF'=> array('name' => 'Sacramento International Airport', 'municipality' => 'Sacramento', 'lat' =>	38.70	, 'long' =>	-121.59	, 'elevation' =>	27	),	
	'SNA'=> array('name' => 'John Wayne Airport-Orange County Airport', 'municipality' => 'Santa Ana', 'lat' =>	33.68	, 'long' =>	-117.87	, 'elevation' =>	56	),	
	'SPI'=> array('name' => 'Abraham Lincoln Capital Airport', 'municipality' => 'Springfield', 'lat' =>	39.84	, 'long' =>	-89.68	, 'elevation' =>	598	),	
	'SPS'=> array('name' => 'Sheppard Air Force Base-Wichita Falls Municipal Airport', 'municipality' => 'Wichita Falls', 'lat' =>	33.99	, 'long' =>	-98.49	, 'elevation' =>	1019	),	
	'SRQ'=> array('name' => 'Sarasota Bradenton International Airport', 'municipality' => 'Sarasota/Bradenton', 'lat' =>	27.40	, 'long' =>	-82.55	, 'elevation' =>	30	),	
	'SSC'=> array('name' => 'Shaw Air Force Base', 'municipality' => 'Sumter', 'lat' =>	33.97	, 'long' =>	-80.47	, 'elevation' =>	241	),	
	'STL'=> array('name' => 'Lambert St Louis International Airport', 'municipality' => 'St Louis', 'lat' =>	38.75	, 'long' =>	-90.37	, 'elevation' =>	618	),	
	'SUS'=> array('name' => 'Spirit of St Louis Airport', 'municipality' => 'St Louis', 'lat' =>	38.66	, 'long' =>	-90.65	, 'elevation' =>	463	),	
	'SUU'=> array('name' => 'Travis Air Force Base', 'municipality' => 'Fairfield', 'lat' =>	38.26	, 'long' =>	-121.93	, 'elevation' =>	62	),	
	'SUX'=> array('name' => 'Sioux Gateway Col. Bud Day Field', 'municipality' => 'Sioux City', 'lat' =>	42.40	, 'long' =>	-96.38	, 'elevation' =>	1098	),	
	'SYR'=> array('name' => 'Syracuse Hancock International Airport', 'municipality' => 'Syracuse', 'lat' =>	43.11	, 'long' =>	-76.11	, 'elevation' =>	421	),	
	'SZL'=> array('name' => 'Whiteman Air Force Base', 'municipality' => 'Knob Noster', 'lat' =>	38.73	, 'long' =>	-93.55	, 'elevation' =>	870	),	
	'TCM'=> array('name' => 'McChord Air Force Base', 'municipality' => 'Tacoma', 'lat' =>	47.14	, 'long' =>	-122.48	, 'elevation' =>	322	),	
	'TIK'=> array('name' => 'Tinker Air Force Base', 'municipality' => 'Oklahoma City', 'lat' =>	35.41	, 'long' =>	-97.39	, 'elevation' =>	1291	),	
	'TLH'=> array('name' => 'Tallahassee Regional Airport', 'municipality' => 'Tallahassee', 'lat' =>	30.40	, 'long' =>	-84.35	, 'elevation' =>	81	),	
	'TOL'=> array('name' => 'Toledo Express Airport', 'municipality' => 'Toledo', 'lat' =>	41.59	, 'long' =>	-83.81	, 'elevation' =>	683	),	
	'TPA'=> array('name' => 'Tampa International Airport', 'municipality' => 'Tampa', 'lat' =>	27.98	, 'long' =>	-82.53	, 'elevation' =>	26	),	
	'TRI'=> array('name' => 'Tri Cities Regional Tn Va Airport', 'municipality' => 'Bristol/Johnson/Kingsport', 'lat' =>	36.48	, 'long' =>	-82.41	, 'elevation' =>	1519	),	
	'TUL'=> array('name' => 'Tulsa International Airport', 'municipality' => 'Tulsa', 'lat' =>	36.20	, 'long' =>	-95.89	, 'elevation' =>	677	),	
	'TUS'=> array('name' => 'Tucson International Airport', 'municipality' => 'Tucson', 'lat' =>	32.12	, 'long' =>	-110.94	, 'elevation' =>	2643	),	
	'TYS'=> array('name' => 'McGhee Tyson Airport', 'municipality' => 'Knoxville', 'lat' =>	35.81	, 'long' =>	-83.99	, 'elevation' =>	981	),	
	'VBG'=> array('name' => 'Vandenberg Air Force Base', 'municipality' => 'Lompoc', 'lat' =>	34.74	, 'long' =>	-120.58	, 'elevation' =>	369	),	
	'VPS'=> array('name' => 'Eglin Air Force Base', 'municipality' => 'Valparaiso', 'lat' =>	30.48	, 'long' =>	-86.53	, 'elevation' =>	87	),	
	'WRB'=> array('name' => 'Robins Air Force Base', 'municipality' => 'Warner Robins', 'lat' =>	32.64	, 'long' =>	-83.59	, 'elevation' =>	294	),	
	'TIA'=> array('name' => 'Tirana International Airport Mother Teresa', 'municipality' => 'Tirana', 'lat' =>	41.41	, 'long' =>	19.72	, 'elevation' =>	126	),	
	'BOJ'=> array('name' => 'Burgas Airport', 'municipality' => 'Burgas', 'lat' =>	42.57	, 'long' =>	27.52	, 'elevation' =>	135	),	
	'PDV'=> array('name' => 'Plovdiv International Airport', 'municipality' => 'Plovdiv', 'lat' =>	42.07	, 'long' =>	24.85	, 'elevation' =>	597	),	
	'SOF'=> array('name' => 'Sofia Airport', 'municipality' => 'Sofia', 'lat' =>	42.70	, 'long' =>	23.41	, 'elevation' =>	1742	),	
	'VAR'=> array('name' => 'Varna Airport', 'municipality' => 'Varna', 'lat' =>	43.23	, 'long' =>	27.83	, 'elevation' =>	230	),	
	'LCA'=> array('name' => 'Larnaca International Airport', 'municipality' => 'Larnarca', 'lat' =>	34.88	, 'long' =>	33.62	, 'elevation' =>	8	),	
	'PFO'=> array('name' => 'Paphos International Airport', 'municipality' => 'Paphos', 'lat' =>	34.72	, 'long' =>	32.49	, 'elevation' =>	41	),	
	'ZAG'=> array('name' => 'Zagreb Airport', 'municipality' => 'Zagreb', 'lat' =>	45.74	, 'long' =>	16.07	, 'elevation' =>	353	),	
	'ALC'=> array('name' => 'Alicante International Airport', 'municipality' => 'Alicante', 'lat' =>	38.28	, 'long' =>	-0.56	, 'elevation' =>	142	),	
	'BCN'=> array('name' => 'Barcelona International Airport', 'municipality' => 'Barcelona', 'lat' =>	41.30	, 'long' =>	2.08	, 'elevation' =>	12	),	
	'MAD'=> array('name' => 'Adolfo Su��rez Madrid���Barajas Airport', 'municipality' => 'Madrid', 'lat' =>	40.49	, 'long' =>	-3.57	, 'elevation' =>	1998	),	
	'AGP'=> array('name' => 'M��laga Airport', 'municipality' => 'M��laga', 'lat' =>	36.67	, 'long' =>	-4.50	, 'elevation' =>	53	),	
	'PMI'=> array('name' => 'Palma De Mallorca Airport', 'municipality' => 'Palma De Mallorca', 'lat' =>	39.55	, 'long' =>	2.74	, 'elevation' =>	27	),	
	'SCQ'=> array('name' => 'Santiago de Compostela Airport', 'municipality' => 'Santiago de Compostela', 'lat' =>	42.90	, 'long' =>	-8.42	, 'elevation' =>	1213	),	
	'BOD'=> array('name' => 'Bordeaux-Merignac Airport', 'municipality' => 'Bordeaux/Merignac', 'lat' =>	44.83	, 'long' =>	-0.72	, 'elevation' =>	162	),	
	'TLS'=> array('name' => 'Toulouse-Blagnac Airport', 'municipality' => 'Toulouse/Blagnac', 'lat' =>	43.63	, 'long' =>	1.36	, 'elevation' =>	499	),	
	'MRS'=> array('name' => 'Marseille Provence Airport', 'municipality' => 'Marseille', 'lat' =>	43.44	, 'long' =>	5.22	, 'elevation' =>	74	),	
	'NCE'=> array('name' => 'Nice-Cote d\'Azur Airport', 'municipality' => 'Nice', 'lat' =>	43.66	, 'long' =>	7.22	, 'elevation' =>	12	),	
	'CDG'=> array('name' => 'Charles de Gaulle International Airport', 'municipality' => 'Paris', 'lat' =>	49.01	, 'long' =>	2.55	, 'elevation' =>	392	),	
	'ORY'=> array('name' => 'Paris-Orly Airport', 'municipality' => 'Paris', 'lat' =>	48.73	, 'long' =>	2.36	, 'elevation' =>	291	),	
	'BSL'=> array('name' => 'EuroAirport Basel-Mulhouse-Freiburg Airport', 'municipality' => 'B��le/Mulhouse', 'lat' =>	47.59	, 'long' =>	7.53	, 'elevation' =>	885	),	
	'ATH'=> array('name' => 'Eleftherios Venizelos International Airport', 'municipality' => 'Athens', 'lat' =>	37.94	, 'long' =>	23.94	, 'elevation' =>	308	),	
	'HER'=> array('name' => 'Heraklion International Nikos Kazantzakis Airport', 'municipality' => 'Heraklion', 'lat' =>	35.34	, 'long' =>	25.18	, 'elevation' =>	115	),	
	'SKG'=> array('name' => 'Thessaloniki Macedonia International Airport', 'municipality' => 'Thessaloniki', 'lat' =>	40.52	, 'long' =>	22.97	, 'elevation' =>	22	),	
	'BUD'=> array('name' => 'Budapest Ferenc Liszt International Airport', 'municipality' => 'Budapest', 'lat' =>	47.44	, 'long' =>	19.26	, 'elevation' =>	495	),	
	'BRI'=> array('name' => 'Bari Karol Wojty��a Airport', 'municipality' => 'Bari', 'lat' =>	41.14	, 'long' =>	16.76	, 'elevation' =>	177	),	
	'CTA'=> array('name' => 'Catania-Fontanarossa Airport', 'municipality' => 'Catania', 'lat' =>	37.47	, 'long' =>	15.07	, 'elevation' =>	39	),	
	'PMO'=> array('name' => 'Falcone���Borsellino Airport', 'municipality' => 'Palermo', 'lat' =>	38.18	, 'long' =>	13.09	, 'elevation' =>	65	),	
	'CAG'=> array('name' => 'Cagliari Elmas Airport', 'municipality' => 'Cagliari', 'lat' =>	39.25	, 'long' =>	9.05	, 'elevation' =>	13	),	
	'MXP'=> array('name' => 'Malpensa International Airport', 'municipality' => 'Milan', 'lat' =>	45.63	, 'long' =>	8.73	, 'elevation' =>	768	),	
	'BGY'=> array('name' => 'Il Caravaggio International Airport', 'municipality' => 'Bergamo', 'lat' =>	45.67	, 'long' =>	9.70	, 'elevation' =>	782	),	
	'TRN'=> array('name' => 'Turin Airport', 'municipality' => 'Torino', 'lat' =>	45.20	, 'long' =>	7.65	, 'elevation' =>	989	),	
	'GOA'=> array('name' => 'Genoa Cristoforo Colombo Airport', 'municipality' => 'Genova', 'lat' =>	44.41	, 'long' =>	8.84	, 'elevation' =>	13	),	
	'LIN'=> array('name' => 'Linate Airport', 'municipality' => 'Milan', 'lat' =>	45.45	, 'long' =>	9.28	, 'elevation' =>	353	),	
	'CUF'=> array('name' => 'Cuneo International Airport', 'municipality' => 'Cuneo', 'lat' =>	44.55	, 'long' =>	7.62	, 'elevation' =>	1267	),	
	'BLQ'=> array('name' => 'Bologna Guglielmo Marconi Airport', 'municipality' => 'Bologna', 'lat' =>	44.54	, 'long' =>	11.29	, 'elevation' =>	123	),	
	'TSF'=> array('name' => 'Treviso-Sant\'Angelo Airport', 'municipality' => 'Treviso', 'lat' =>	45.65	, 'long' =>	12.19	, 'elevation' =>	59	),	
	'VRN'=> array('name' => 'Verona Villafranca Airport', 'municipality' => 'Verona', 'lat' =>	45.40	, 'long' =>	10.89	, 'elevation' =>	239	),	
	'VCE'=> array('name' => 'Venice Marco Polo Airport', 'municipality' => 'Venice', 'lat' =>	45.51	, 'long' =>	12.35	, 'elevation' =>	7	),	
	'CIA'=> array('name' => 'Ciampino���G. B. Pastine International Airport', 'municipality' => 'Roma', 'lat' =>	41.80	, 'long' =>	12.59	, 'elevation' =>	427	),	
	'FCO'=> array('name' => 'Leonardo da Vinci���Fiumicino Airport', 'municipality' => 'Rome', 'lat' =>	41.80	, 'long' =>	12.25	, 'elevation' =>	15	),	
	'NAP'=> array('name' => 'Naples International Airport', 'municipality' => 'N��poli', 'lat' =>	40.89	, 'long' =>	14.29	, 'elevation' =>	294	),	
	'PSA'=> array('name' => 'Pisa International Airport', 'municipality' => 'Pisa', 'lat' =>	43.68	, 'long' =>	10.39	, 'elevation' =>	6	),	
	'LJU'=> array('name' => 'Ljubljana Jo��e Pu��nik Airport', 'municipality' => 'Ljubljana', 'lat' =>	46.22	, 'long' =>	14.46	, 'elevation' =>	1273	),	
	'PRG'=> array('name' => 'Ruzyn�� International Airport', 'municipality' => 'Prague', 'lat' =>	50.10	, 'long' =>	14.26	, 'elevation' =>	1247	),	
	'TLV'=> array('name' => 'Ben Gurion International Airport', 'municipality' => 'Tel Aviv', 'lat' =>	32.01	, 'long' =>	34.89	, 'elevation' =>	135	),	
	'VDA'=> array('name' => 'Ovda International Airport', 'municipality' => 'Eilat', 'lat' =>	29.94	, 'long' =>	34.94	, 'elevation' =>	1492	),	
	'MLA'=> array('name' => 'Malta International Airport', 'municipality' => 'Luqa', 'lat' =>	35.86	, 'long' =>	14.48	, 'elevation' =>	300	),	
	'VIE'=> array('name' => 'Vienna International Airport', 'municipality' => 'Vienna', 'lat' =>	48.11	, 'long' =>	16.57	, 'elevation' =>	600	),	
	'FAO'=> array('name' => 'Faro Airport', 'municipality' => 'Faro', 'lat' =>	37.01	, 'long' =>	-7.97	, 'elevation' =>	24	),	
	'TER'=> array('name' => 'Lajes Field', 'municipality' => 'Lajes', 'lat' =>	38.76	, 'long' =>	-27.09	, 'elevation' =>	180	),	
	'PDL'=> array('name' => 'Jo��o Paulo II Airport', 'municipality' => 'Ponta Delgada', 'lat' =>	37.74	, 'long' =>	-25.70	, 'elevation' =>	259	),	
	'OPO'=> array('name' => 'Francisco de S�� Carneiro Airport', 'municipality' => 'Porto', 'lat' =>	41.25	, 'long' =>	-8.68	, 'elevation' =>	228	),	
	'LIS'=> array('name' => 'Lisbon Portela Airport', 'municipality' => 'Lisbon', 'lat' =>	38.78	, 'long' =>	-9.14	, 'elevation' =>	374	),	
	'SJJ'=> array('name' => 'Sarajevo International Airport', 'municipality' => 'Sarajevo', 'lat' =>	43.82	, 'long' =>	18.33	, 'elevation' =>	1708	),	
	'OTP'=> array('name' => 'Henri Coand�� International Airport', 'municipality' => 'Bucharest', 'lat' =>	44.57	, 'long' =>	26.10	, 'elevation' =>	314	),	
	'GVA'=> array('name' => 'Geneva Cointrin International Airport', 'municipality' => 'Geneva', 'lat' =>	46.24	, 'long' =>	6.11	, 'elevation' =>	1411	),	
	'ZRH'=> array('name' => 'Z��rich Airport', 'municipality' => 'Zurich', 'lat' =>	47.46	, 'long' =>	8.55	, 'elevation' =>	1416	),	
	'ESB'=> array('name' => 'Esenbo��a International Airport', 'municipality' => 'Ankara', 'lat' =>	40.13	, 'long' =>	33.00	, 'elevation' =>	3125	),	
	'ADA'=> array('name' => 'Adana Airport', 'municipality' => 'Adana', 'lat' =>	36.98	, 'long' =>	35.28	, 'elevation' =>	65	),	
	'AYT'=> array('name' => 'Antalya International Airport', 'municipality' => 'Antalya', 'lat' =>	36.90	, 'long' =>	30.80	, 'elevation' =>	177	),	
	'GZT'=> array('name' => 'Gaziantep International Airport', 'municipality' => 'Gaziantep', 'lat' =>	36.95	, 'long' =>	37.48	, 'elevation' =>	2315	),	
	'NAV'=> array('name' => 'Nev��ehir Kapadokya International Airport', 'municipality' => 'Nev��ehir', 'lat' =>	38.77	, 'long' =>	34.53	, 'elevation' =>	3100	),	
	'IST'=> array('name' => 'Atat��rk International Airport', 'municipality' => 'Istanbul', 'lat' =>	40.98	, 'long' =>	28.81	, 'elevation' =>	163	),	
	'ADB'=> array('name' => 'Adnan Menderes International Airport', 'municipality' => '��zmir', 'lat' =>	38.29	, 'long' =>	27.16	, 'elevation' =>	412	),	
	'DLM'=> array('name' => 'Dalaman International Airport', 'municipality' => 'Dalaman', 'lat' =>	36.71	, 'long' =>	28.79	, 'elevation' =>	20	),	
	'ERZ'=> array('name' => 'Erzurum International Airport', 'municipality' => 'Erzurum', 'lat' =>	39.96	, 'long' =>	41.17	, 'elevation' =>	5763	),	
	'TZX'=> array('name' => 'Trabzon International Airport', 'municipality' => 'Trabzon', 'lat' =>	41.00	, 'long' =>	39.79	, 'elevation' =>	104	),	
	'ISE'=> array('name' => 'S��leyman Demirel International Airport', 'municipality' => 'Isparta', 'lat' =>	37.86	, 'long' =>	30.37	, 'elevation' =>	2835	),	
	'BJV'=> array('name' => 'Milas Bodrum International Airport', 'municipality' => 'Bodrum', 'lat' =>	37.25	, 'long' =>	27.66	, 'elevation' =>	21	),	
	'SAW'=> array('name' => 'Sabiha G��k��en International Airport', 'municipality' => 'Istanbul', 'lat' =>	40.90	, 'long' =>	29.31	, 'elevation' =>	312	),	
	'BEG'=> array('name' => 'Belgrade Nikola Tesla Airport', 'municipality' => 'Belgrade', 'lat' =>	44.82	, 'long' =>	20.31	, 'elevation' =>	335	),	
	'TGD'=> array('name' => 'Podgorica Airport', 'municipality' => 'Podgorica', 'lat' =>	42.36	, 'long' =>	19.25	, 'elevation' =>	141	),	
	'BTS'=> array('name' => 'M. R. ��tef��nik Airport', 'municipality' => 'Bratislava', 'lat' =>	48.17	, 'long' =>	17.21	, 'elevation' =>	436	),	
	'PUJ'=> array('name' => 'Punta Cana International Airport', 'municipality' => 'Punta Cana', 'lat' =>	18.57	, 'long' =>	-68.36	, 'elevation' =>	47	),	
	'SDQ'=> array('name' => 'Las Am��ricas International Airport', 'municipality' => 'Santo Domingo', 'lat' =>	18.43	, 'long' =>	-69.67	, 'elevation' =>	59	),	
	'KIN'=> array('name' => 'Norman Manley International Airport', 'municipality' => 'Kingston', 'lat' =>	17.94	, 'long' =>	-76.79	, 'elevation' =>	10	),	
	'ACA'=> array('name' => 'General Juan N Alvarez International Airport', 'municipality' => 'Acapulco', 'lat' =>	16.76	, 'long' =>	-99.75	, 'elevation' =>	16	),	
	'GDL'=> array('name' => 'Don Miguel Hidalgo Y Costilla International Airport', 'municipality' => 'Guadalajara', 'lat' =>	20.52	, 'long' =>	-103.31	, 'elevation' =>	5016	),	
	'HMO'=> array('name' => 'General Ignacio P. Garcia International Airport', 'municipality' => 'Hermosillo', 'lat' =>	29.10	, 'long' =>	-111.05	, 'elevation' =>	627	),	
	'MEX'=> array('name' => 'Licenciado Benito Juarez International Airport', 'municipality' => 'Mexico City', 'lat' =>	19.44	, 'long' =>	-99.07	, 'elevation' =>	7316	),	
	'MTY'=> array('name' => 'General Mariano Escobedo International Airport', 'municipality' => 'Monterrey', 'lat' =>	25.78	, 'long' =>	-100.11	, 'elevation' =>	1278	),	
	'PVR'=> array('name' => 'Licenciado Gustavo D��az Ordaz International Airport', 'municipality' => 'Puerto Vallarta', 'lat' =>	20.68	, 'long' =>	-105.25	, 'elevation' =>	23	),	
	'SJD'=> array('name' => 'Los Cabos International Airport', 'municipality' => 'San Jos�� del Cabo', 'lat' =>	23.15	, 'long' =>	-109.72	, 'elevation' =>	374	),	
	'TIJ'=> array('name' => 'General Abelardo L. Rodr��guez International Airport', 'municipality' => 'Tijuana', 'lat' =>	32.54	, 'long' =>	-116.97	, 'elevation' =>	489	),	
	'CUN'=> array('name' => 'Canc��n International Airport', 'municipality' => 'Canc��n', 'lat' =>	21.04	, 'long' =>	-86.88	, 'elevation' =>	22	),	
	'PTY'=> array('name' => 'Tocumen International Airport', 'municipality' => 'Tocumen', 'lat' =>	9.07	, 'long' =>	-79.38	, 'elevation' =>	135	),	
	'HAV'=> array('name' => 'Jos�� Mart�� International Airport', 'municipality' => 'Havana', 'lat' =>	22.99	, 'long' =>	-82.41	, 'elevation' =>	210	),	
	'VRA'=> array('name' => 'Juan Gualberto Gomez International Airport', 'municipality' => 'Varadero', 'lat' =>	23.03	, 'long' =>	-81.44	, 'elevation' =>	210	),	
	'GCM'=> array('name' => 'Owen Roberts International Airport', 'municipality' => 'Georgetown', 'lat' =>	19.29	, 'long' =>	-81.36	, 'elevation' =>	8	),	
	'NAS'=> array('name' => 'Lynden Pindling International Airport', 'municipality' => 'Nassau', 'lat' =>	25.04	, 'long' =>	-77.47	, 'elevation' =>	16	),	
	'BZE'=> array('name' => 'Philip S. W. Goldson International Airport', 'municipality' => 'Belize City', 'lat' =>	17.54	, 'long' =>	-88.31	, 'elevation' =>	15	),	
	'RAR'=> array('name' => 'Rarotonga International Airport', 'municipality' => 'Avarua', 'lat' =>	-21.20	, 'long' =>	-159.81	, 'elevation' =>	19	),	
	'AKL'=> array('name' => 'Auckland International Airport', 'municipality' => 'Auckland', 'lat' =>	-37.01	, 'long' =>	174.79	, 'elevation' =>	23	),	
	'CHC'=> array('name' => 'Christchurch International Airport', 'municipality' => 'Christchurch', 'lat' =>	-43.49	, 'long' =>	172.53	, 'elevation' =>	123	),	
	'WLG'=> array('name' => 'Wellington International Airport', 'municipality' => 'Wellington', 'lat' =>	-41.33	, 'long' =>	174.80	, 'elevation' =>	41	),	
	'BAH'=> array('name' => 'Bahrain International Airport', 'municipality' => 'Manama', 'lat' =>	26.27	, 'long' =>	50.63	, 'elevation' =>	6	),	
	'DMM'=> array('name' => 'King Fahd International Airport', 'municipality' => 'Ad Dammam', 'lat' =>	26.47	, 'long' =>	49.80	, 'elevation' =>	72	),	
	'DHA'=> array('name' => 'King Abdulaziz Air Base', 'municipality' => '', 'lat' =>	26.27	, 'long' =>	50.15	, 'elevation' =>	84	),	
	'JED'=> array('name' => 'King Abdulaziz International Airport', 'municipality' => 'Jeddah', 'lat' =>	21.68	, 'long' =>	39.16	, 'elevation' =>	48	),	
	'MED'=> array('name' => 'Prince Mohammad Bin Abdulaziz Airport', 'municipality' => 'Medina', 'lat' =>	24.55	, 'long' =>	39.71	, 'elevation' =>	2151	),	
	'RUH'=> array('name' => 'King Khaled International Airport', 'municipality' => 'Riyadh', 'lat' =>	24.96	, 'long' =>	46.70	, 'elevation' =>	2049	),	
	'IKA'=> array('name' => 'Imam Khomeini International Airport', 'municipality' => 'Tehran', 'lat' =>	35.42	, 'long' =>	51.15	, 'elevation' =>	3305	),	
	'THR'=> array('name' => 'Mehrabad International Airport', 'municipality' => 'Tehran', 'lat' =>	35.69	, 'long' =>	51.31	, 'elevation' =>	3962	),	
	'MHD'=> array('name' => 'Mashhad International Airport', 'municipality' => 'Mashhad', 'lat' =>	36.24	, 'long' =>	59.64	, 'elevation' =>	3263	),	
	'SYZ'=> array('name' => 'Shiraz Shahid Dastghaib International Airport', 'municipality' => 'Shiraz', 'lat' =>	29.54	, 'long' =>	52.59	, 'elevation' =>	4920	),	
	'TBZ'=> array('name' => 'Tabriz International Airport', 'municipality' => 'Tabriz', 'lat' =>	38.13	, 'long' =>	46.24	, 'elevation' =>	4459	),	
	'AMM'=> array('name' => 'Queen Alia International Airport', 'municipality' => 'Amman', 'lat' =>	31.72	, 'long' =>	35.99	, 'elevation' =>	2395	),	
	'KWI'=> array('name' => 'Kuwait International Airport', 'municipality' => 'Kuwait City', 'lat' =>	29.23	, 'long' =>	47.97	, 'elevation' =>	206	),	
	'BEY'=> array('name' => 'Beirut Rafic Hariri International Airport', 'municipality' => 'Beirut', 'lat' =>	33.82	, 'long' =>	35.49	, 'elevation' =>	87	),	
	'DQM'=> array('name' => 'Duqm International Airport', 'municipality' => 'Duqm', 'lat' =>	19.50	, 'long' =>	57.64	, 'elevation' =>	380	),	
	'AUH'=> array('name' => 'Abu Dhabi International Airport', 'municipality' => 'Abu Dhabi', 'lat' =>	24.43	, 'long' =>	54.65	, 'elevation' =>	88	),	
	'DXB'=> array('name' => 'Dubai International Airport', 'municipality' => 'Dubai', 'lat' =>	25.25	, 'long' =>	55.36	, 'elevation' =>	62	),	
	'DWC'=> array('name' => 'Al Maktoum International Airport', 'municipality' => 'Jebel Ali', 'lat' =>	24.90	, 'long' =>	55.16	, 'elevation' =>	114	),	
	'SHJ'=> array('name' => 'Sharjah International Airport', 'municipality' => 'Sharjah', 'lat' =>	25.33	, 'long' =>	55.52	, 'elevation' =>	111	),	
	'MCT'=> array('name' => 'Muscat International Airport', 'municipality' => 'Muscat', 'lat' =>	23.59	, 'long' =>	58.28	, 'elevation' =>	48	),	
	'ISB'=> array('name' => 'Benazir Bhutto International Airport', 'municipality' => 'Islamabad', 'lat' =>	33.62	, 'long' =>	73.10	, 'elevation' =>	1668	),	
	'SKT'=> array('name' => 'Sialkot Airport', 'municipality' => 'Sialkot', 'lat' =>	32.54	, 'long' =>	74.36	, 'elevation' =>	837	),	
	'BGW'=> array('name' => 'Baghdad International Airport', 'municipality' => 'Baghdad', 'lat' =>	33.26	, 'long' =>	44.23	, 'elevation' =>	114	),	
	'BSR'=> array('name' => 'Basrah International Airport', 'municipality' => 'Basrah', 'lat' =>	30.55	, 'long' =>	47.66	, 'elevation' =>	11	),	
	'ALP'=> array('name' => 'Aleppo International Airport', 'municipality' => 'Aleppo', 'lat' =>	36.18	, 'long' =>	37.22	, 'elevation' =>	1276	),	
	'DAM'=> array('name' => 'Damascus International Airport', 'municipality' => 'Damascus', 'lat' =>	33.41	, 'long' =>	36.52	, 'elevation' =>	2020	),	
	'LTK'=> array('name' => 'Bassel Al-Assad International Airport', 'municipality' => 'Latakia', 'lat' =>	35.40	, 'long' =>	35.95	, 'elevation' =>	157	),	
	'FAI'=> array('name' => 'Fairbanks International Airport', 'municipality' => 'Fairbanks', 'lat' =>	64.82	, 'long' =>	-147.86	, 'elevation' =>	439	),	
	'ANC'=> array('name' => 'Ted Stevens Anchorage International Airport', 'municipality' => 'Anchorage', 'lat' =>	61.17	, 'long' =>	-150.00	, 'elevation' =>	152	),	
	'GUM'=> array('name' => 'Antonio B. Won Pat International Airport', 'municipality' => 'Hag��t��a, Guam International Airport', 'lat' =>	13.48	, 'long' =>	144.80	, 'elevation' =>	298	),	
	'CGY'=> array('name' => 'Laguindingan Airport', 'municipality' => 'Cagayan de Oro City', 'lat' =>	8.61	, 'long' =>	124.46	, 'elevation' =>	190	),	
	'HNL'=> array('name' => 'Honolulu International Airport', 'municipality' => 'Honolulu', 'lat' =>	21.32	, 'long' =>	-157.92	, 'elevation' =>	13	),	
	'DOH'=> array('name' => 'Hamad International Airport', 'municipality' => 'Doha', 'lat' =>	25.27	, 'long' =>	51.61	, 'elevation' =>	13	),	
	'KNH'=> array('name' => 'Kinmen Airport', 'municipality' => 'Shang-I', 'lat' =>	24.43	, 'long' =>	118.36	, 'elevation' =>	93	),	
	'KHH'=> array('name' => 'Kaohsiung International Airport', 'municipality' => 'Kaohsiung City', 'lat' =>	22.58	, 'long' =>	120.35	, 'elevation' =>	31	),	
	'TPE'=> array('name' => 'Taiwan Taoyuan International Airport', 'municipality' => 'Taipei', 'lat' =>	25.08	, 'long' =>	121.23	, 'elevation' =>	106	),	
	'NRT'=> array('name' => 'Narita International Airport', 'municipality' => 'Tokyo', 'lat' =>	35.76	, 'long' =>	140.39	, 'elevation' =>	141	),	
	'KIX'=> array('name' => 'Kansai International Airport', 'municipality' => 'Osaka', 'lat' =>	34.43	, 'long' =>	135.24	, 'elevation' =>	26	),	
	'CTS'=> array('name' => 'New Chitose Airport', 'municipality' => 'Chitose / Tomakomai', 'lat' =>	42.78	, 'long' =>	141.69	, 'elevation' =>	82	),	
	'FUK'=> array('name' => 'Fukuoka Airport', 'municipality' => 'Fukuoka', 'lat' =>	33.59	, 'long' =>	130.45	, 'elevation' =>	32	),	
	'KOJ'=> array('name' => 'Kagoshima Airport', 'municipality' => 'Kagoshima', 'lat' =>	31.80	, 'long' =>	130.72	, 'elevation' =>	906	),	
	'NGO'=> array('name' => 'Chubu Centrair International Airport', 'municipality' => 'Tokoname', 'lat' =>	34.86	, 'long' =>	136.80	, 'elevation' =>	15	),	
	'FSZ'=> array('name' => 'Mt. Fuji Shizuoka Airport', 'municipality' => 'Makinohara / Shimada', 'lat' =>	34.80	, 'long' =>	138.19	, 'elevation' =>	433	),	
	'ITM'=> array('name' => 'Osaka International Airport', 'municipality' => 'Osaka', 'lat' =>	34.79	, 'long' =>	135.44	, 'elevation' =>	50	),	
	'HND'=> array('name' => 'Tokyo International Airport', 'municipality' => 'Tokyo', 'lat' =>	35.55	, 'long' =>	139.78	, 'elevation' =>	35	),	
	'OKO'=> array('name' => 'Yokota Air Base', 'municipality' => 'Fussa', 'lat' =>	35.75	, 'long' =>	139.35	, 'elevation' =>	463	),	
	'MWX'=> array('name' => 'Muan International Airport', 'municipality' => 'Muan', 'lat' =>	34.99	, 'long' =>	126.38	, 'elevation' =>	35	),	
	'KUV'=> array('name' => 'Kunsan Air Base', 'municipality' => 'Kunsan', 'lat' =>	35.90	, 'long' =>	126.62	, 'elevation' =>	29	),	
	'CJU'=> array('name' => 'Jeju International Airport', 'municipality' => 'Jeju City', 'lat' =>	33.51	, 'long' =>	126.49	, 'elevation' =>	118	),	
	'PUS'=> array('name' => 'Gimhae International Airport', 'municipality' => 'Busan', 'lat' =>	35.18	, 'long' =>	128.94	, 'elevation' =>	6	),	
	'ICN'=> array('name' => 'Incheon International Airport', 'municipality' => 'Seoul', 'lat' =>	37.47	, 'long' =>	126.45	, 'elevation' =>	23	),	
	'OSN'=> array('name' => 'Osan Air Base', 'municipality' => '', 'lat' =>	37.09	, 'long' =>	127.03	, 'elevation' =>	38	),	
	'GMP'=> array('name' => 'Gimpo International Airport', 'municipality' => 'Seoul', 'lat' =>	37.56	, 'long' =>	126.79	, 'elevation' =>	58	),	
	'CJJ'=> array('name' => 'Cheongju International Airport', 'municipality' => 'Cheongju', 'lat' =>	36.72	, 'long' =>	127.50	, 'elevation' =>	191	),	
	'OKA'=> array('name' => 'Naha Airport', 'municipality' => 'Naha', 'lat' =>	26.20	, 'long' =>	127.65	, 'elevation' =>	12	),	
	'DNA'=> array('name' => 'Kadena Air Base', 'municipality' => '', 'lat' =>	26.36	, 'long' =>	127.77	, 'elevation' =>	143	),	
	'CRK'=> array('name' => 'Clark International Airport', 'municipality' => 'Angeles City', 'lat' =>	15.19	, 'long' =>	120.56	, 'elevation' =>	484	),	
	'MNL'=> array('name' => 'Ninoy Aquino International Airport', 'municipality' => 'Manila', 'lat' =>	14.51	, 'long' =>	121.02	, 'elevation' =>	75	),	
	'DVO'=> array('name' => 'Francisco Bangoy International Airport', 'municipality' => 'Davao City', 'lat' =>	7.13	, 'long' =>	125.65	, 'elevation' =>	96	),	
	'CEB'=> array('name' => 'Mactan Cebu International Airport', 'municipality' => 'Lapu-Lapu City', 'lat' =>	10.31	, 'long' =>	123.98	, 'elevation' =>	31	),	
	'GRV'=> array('name' => 'Grozny North Airport', 'municipality' => 'Grozny', 'lat' =>	43.39	, 'long' =>	45.70	, 'elevation' => 'UNK' ),	
	'EZE'=> array('name' => 'Ministro Pistarini International Airport', 'municipality' => 'Buenos Aires', 'lat' =>	-34.82	, 'long' =>	-58.54	, 'elevation' =>	67	),	
	'BEL'=> array('name' => 'Val de Cans/J��lio Cezar Ribeiro International Airport', 'municipality' => 'Bel��m', 'lat' =>	-1.38	, 'long' =>	-48.48	, 'elevation' =>	54	),	
	'BSB'=> array('name' => 'Presidente Juscelino Kubistschek International Airport', 'municipality' => 'Bras��lia', 'lat' =>	-15.87	, 'long' =>	-47.92	, 'elevation' =>	3497	),	
	'CNF'=> array('name' => 'Tancredo Neves International Airport', 'municipality' => 'Belo Horizonte', 'lat' =>	-19.62	, 'long' =>	-43.97	, 'elevation' =>	2715	),	
	'CWB'=> array('name' => 'Afonso Pena Airport', 'municipality' => 'Curitiba', 'lat' =>	-25.53	, 'long' =>	-49.18	, 'elevation' =>	2988	),	
	'FLN'=> array('name' => 'Herc��lio Luz International Airport', 'municipality' => 'Florian��polis', 'lat' =>	-27.67	, 'long' =>	-48.55	, 'elevation' =>	16	),	
	'GIG'=> array('name' => 'Rio Gale��o ��� Tom Jobim International Airport', 'municipality' => 'Rio De Janeiro', 'lat' =>	-22.81	, 'long' =>	-43.25	, 'elevation' =>	28	),	
	'GRU'=> array('name' => 'Guarulhos - Governador Andr�� Franco Montoro International Airport', 'municipality' => 'S��o Paulo', 'lat' =>	-23.44	, 'long' =>	-46.47	, 'elevation' =>	2459	),	
	'NAT'=> array('name' => 'Governador Alu��zio Alves International Airport', 'municipality' => 'Natal', 'lat' =>	-5.77	, 'long' =>	-35.38	, 'elevation' =>	272	),	
	'CGH'=> array('name' => 'Congonhas Airport', 'municipality' => 'S��o Paulo', 'lat' =>	-23.63	, 'long' =>	-46.66	, 'elevation' =>	2631	),	
	'SSA'=> array('name' => 'Deputado Luiz Eduardo Magalh��es International Airport', 'municipality' => 'Salvador', 'lat' =>	-12.91	, 'long' =>	-38.32	, 'elevation' =>	64	),	
	'SCL'=> array('name' => 'Comodoro Arturo Merino Ben��tez International Airport', 'municipality' => 'Santiago', 'lat' =>	-33.39	, 'long' =>	-70.79	, 'elevation' =>	1555	),	
	'LTX'=> array('name' => 'Cotopaxi International Airport', 'municipality' => 'Latacunga', 'lat' =>	-0.91	, 'long' =>	-78.62	, 'elevation' =>	9205	),	
	'UIO'=> array('name' => 'Mariscal Sucre International Airport', 'municipality' => 'Quito', 'lat' =>	-0.13	, 'long' =>	-78.36	, 'elevation' =>	7841	),	
	'BOG'=> array('name' => 'El Dorado International Airport', 'municipality' => 'Bogota', 'lat' =>	4.70	, 'long' =>	-74.15	, 'elevation' =>	8361	),	
	'LIM'=> array('name' => 'Jorge Ch��vez International Airport', 'municipality' => 'Lima', 'lat' =>	-12.02	, 'long' =>	-77.11	, 'elevation' =>	113	),	
	'CUZ'=> array('name' => 'Alejandro Velasco Astete International Airport', 'municipality' => 'Cusco', 'lat' =>	-13.54	, 'long' =>	-71.94	, 'elevation' =>	10860	),	
	'MVD'=> array('name' => 'Carrasco International /General C L Berisso Airport', 'municipality' => 'Montevideo', 'lat' =>	-34.84	, 'long' =>	-56.03	, 'elevation' =>	105	),	
	'SJU'=> array('name' => 'Luis Munoz Marin International Airport', 'municipality' => 'San Juan', 'lat' =>	18.44	, 'long' =>	-66.00	, 'elevation' =>	9	),	
	'NBE'=> array('name' => 'Enfidha - Hammamet International Airport', 'municipality' => 'Enfidha', 'lat' =>	36.08	, 'long' =>	10.44	, 'elevation' =>	21	),	
	'SXM'=> array('name' => 'Princess Juliana International Airport', 'municipality' => 'Saint Martin', 'lat' =>	18.04	, 'long' =>	-63.11	, 'elevation' =>	13	),	
	'ALA'=> array('name' => 'Almaty Airport', 'municipality' => 'Almaty', 'lat' =>	43.35	, 'long' =>	77.04	, 'elevation' =>	2234	),	
	'TSE'=> array('name' => 'Astana International Airport', 'municipality' => 'Astana', 'lat' =>	51.02	, 'long' =>	71.47	, 'elevation' =>	1165	),	
	'FRU'=> array('name' => 'Manas International Airport', 'municipality' => 'Bishkek', 'lat' =>	43.06	, 'long' =>	74.48	, 'elevation' =>	2058	),	
	'KGF'=> array('name' => 'Sary-Arka Airport', 'municipality' => 'Karaganda', 'lat' =>	49.67	, 'long' =>	73.33	, 'elevation' =>	1765	),	
	'GYD'=> array('name' => 'Heydar Aliyev International Airport', 'municipality' => 'Baku', 'lat' =>	40.47	, 'long' =>	50.05	, 'elevation' =>	10	),	
	'EVN'=> array('name' => 'Zvartnots International Airport', 'municipality' => 'Yerevan', 'lat' =>	40.15	, 'long' =>	44.40	, 'elevation' =>	2838	),	
	'TBS'=> array('name' => 'Tbilisi International Airport', 'municipality' => 'Tbilisi', 'lat' =>	41.67	, 'long' =>	44.95	, 'elevation' =>	1624	),	
	'KHV'=> array('name' => 'Khabarovsk-Novy Airport', 'municipality' => 'Khabarovsk', 'lat' =>	48.53	, 'long' =>	135.19	, 'elevation' =>	244	),	
	'KBP'=> array('name' => 'Boryspil International Airport', 'municipality' => 'Kiev', 'lat' =>	50.35	, 'long' =>	30.89	, 'elevation' =>	427	),	
	'DOK'=> array('name' => 'Donetsk International Airport', 'municipality' => 'Donetsk', 'lat' =>	48.07	, 'long' =>	37.74	, 'elevation' =>	791	),	
	'SIP'=> array('name' => 'Simferopol International Airport', 'municipality' => 'Simferopol', 'lat' =>	45.05	, 'long' =>	33.98	, 'elevation' =>	639	),	
	'HRK'=> array('name' => 'Kharkiv International Airport', 'municipality' => 'Kharkiv', 'lat' =>	49.92	, 'long' =>	36.29	, 'elevation' =>	508	),	
	'ODS'=> array('name' => 'Odessa International Airport', 'municipality' => 'Odessa', 'lat' =>	46.43	, 'long' =>	30.68	, 'elevation' =>	172	),	
	'LED'=> array('name' => 'Pulkovo Airport', 'municipality' => 'St. Petersburg', 'lat' =>	59.80	, 'long' =>	30.26	, 'elevation' =>	78	),	
	'MSQ'=> array('name' => 'Minsk National Airport', 'municipality' => 'Minsk', 'lat' =>	53.88	, 'long' =>	28.03	, 'elevation' =>	670	),	
	'KJA'=> array('name' => 'Yemelyanovo Airport', 'municipality' => 'Krasnoyarsk', 'lat' =>	56.17	, 'long' =>	92.49	, 'elevation' =>	942	),	
	'OVB'=> array('name' => 'Tolmachevo Airport', 'municipality' => 'Novosibirsk', 'lat' =>	55.01	, 'long' =>	82.65	, 'elevation' =>	365	),	
	'ROV'=> array('name' => 'Rostov-on-Don Airport', 'municipality' => 'Rostov-on-Don', 'lat' =>	47.26	, 'long' =>	39.82	, 'elevation' =>	280	),	
	'AER'=> array('name' => 'Sochi International Airport', 'municipality' => 'Sochi', 'lat' =>	43.45	, 'long' =>	39.96	, 'elevation' =>	89	),	
	'SVX'=> array('name' => 'Koltsovo Airport', 'municipality' => 'Yekaterinburg', 'lat' =>	56.74	, 'long' =>	60.80	, 'elevation' =>	764	),	
	'TAS'=> array('name' => 'Tashkent International Airport', 'municipality' => 'Tashkent', 'lat' =>	41.26	, 'long' =>	69.28	, 'elevation' =>	1417	),	
	'DME'=> array('name' => 'Domodedovo International Airport', 'municipality' => 'Moscow', 'lat' =>	55.41	, 'long' =>	37.91	, 'elevation' =>	588	),	
	'SVO'=> array('name' => 'Sheremetyevo International Airport', 'municipality' => 'Moscow', 'lat' =>	55.97	, 'long' =>	37.41	, 'elevation' =>	622	),	
	'CKL'=> array('name' => 'Chkalovskiy Airport', 'municipality' => 'Moscow', 'lat' =>	55.88	, 'long' =>	38.06	, 'elevation' =>	499	),	
	'VKO'=> array('name' => 'Vnukovo International Airport', 'municipality' => 'Moscow', 'lat' =>	55.59	, 'long' =>	37.26	, 'elevation' =>	685	),	
	'KZN'=> array('name' => 'Kazan International Airport', 'municipality' => 'Kazan', 'lat' =>	55.61	, 'long' =>	49.28	, 'elevation' =>	411	),	
	'UFA'=> array('name' => 'Ufa International Airport', 'municipality' => 'Ufa', 'lat' =>	54.56	, 'long' =>	55.87	, 'elevation' =>	449	),	
	'KUF'=> array('name' => 'Kurumoch International Airport', 'municipality' => 'Samara', 'lat' =>	53.50	, 'long' =>	50.16	, 'elevation' =>	477	),	
	'BOM'=> array('name' => 'Chhatrapati Shivaji International Airport', 'municipality' => 'Mumbai', 'lat' =>	19.09	, 'long' =>	72.87	, 'elevation' =>	39	),	
	'GOI'=> array('name' => 'Dabolim Airport', 'municipality' => 'Vasco da Gama', 'lat' =>	15.38	, 'long' =>	73.83	, 'elevation' =>	150	),	
	'CMB'=> array('name' => 'Bandaranaike International Colombo Airport', 'municipality' => 'Colombo', 'lat' =>	7.18	, 'long' =>	79.88	, 'elevation' =>	30	),	
	'HRI'=> array('name' => 'Mattala Rajapaksa International Airport', 'municipality' => '', 'lat' =>	6.28	, 'long' =>	81.12	, 'elevation' =>	157	),	
	'PNH'=> array('name' => 'Phnom Penh International Airport', 'municipality' => 'Phnom Penh', 'lat' =>	11.55	, 'long' =>	104.84	, 'elevation' =>	40	),	
	'REP'=> array('name' => 'Siem Reap International Airport', 'municipality' => 'Siem Reap', 'lat' =>	13.41	, 'long' =>	103.81	, 'elevation' =>	60	),	
	'CCU'=> array('name' => 'Netaji Subhash Chandra Bose International Airport', 'municipality' => 'Kolkata', 'lat' =>	22.65	, 'long' =>	88.45	, 'elevation' =>	16	),	
	'HKG'=> array('name' => 'Chek Lap Kok International Airport', 'municipality' => 'Hong Kong', 'lat' =>	22.31	, 'long' =>	113.92	, 'elevation' =>	28	),	
	'ATQ'=> array('name' => 'Sri Guru Ram Dass Jee International Airport', 'municipality' => 'Amritsar', 'lat' =>	31.71	, 'long' =>	74.80	, 'elevation' =>	756	),	
	'DEL'=> array('name' => 'Indira Gandhi International Airport', 'municipality' => 'New Delhi', 'lat' =>	28.57	, 'long' =>	77.10	, 'elevation' =>	777	),	
	'SLV'=> array('name' => 'Shimla Airport', 'municipality' => '', 'lat' =>	31.08	, 'long' =>	77.07	, 'elevation' =>	5072	),	
	'MFM'=> array('name' => 'Macau International Airport', 'municipality' => 'Taipa', 'lat' =>	22.15	, 'long' =>	113.59	, 'elevation' =>	20	),	
	'BLR'=> array('name' => 'Bengaluru International Airport', 'municipality' => 'Bangalore', 'lat' =>	13.20	, 'long' =>	77.71	, 'elevation' =>	3000	),	
	'COK'=> array('name' => 'Cochin International Airport', 'municipality' => 'Cochin', 'lat' =>	10.15	, 'long' =>	76.40	, 'elevation' =>	30	),	
	'CCJ'=> array('name' => 'Calicut International Airport', 'municipality' => 'Calicut', 'lat' =>	11.14	, 'long' =>	75.96	, 'elevation' =>	342	),	
	'HYD'=> array('name' => 'Rajiv Gandhi International Airport', 'municipality' => 'Hyderabad', 'lat' =>	17.23	, 'long' =>	78.43	, 'elevation' =>	2024	),	
	'MAA'=> array('name' => 'Chennai International Airport', 'municipality' => 'Chennai', 'lat' =>	12.99	, 'long' =>	80.17	, 'elevation' =>	52	),	
	'TRV'=> array('name' => 'Trivandrum International Airport', 'municipality' => 'Thiruvananthapuram', 'lat' =>	8.48	, 'long' =>	76.92	, 'elevation' =>	15	),	
	'MLE'=> array('name' => 'Mal�� International Airport', 'municipality' => 'Mal��', 'lat' =>	4.19	, 'long' =>	73.53	, 'elevation' =>	6	),	
	'DMK'=> array('name' => 'Don Mueang International Airport', 'municipality' => 'Bangkok', 'lat' =>	13.91	, 'long' =>	100.61	, 'elevation' =>	9	),	
	'BKK'=> array('name' => 'Suvarnabhumi Airport', 'municipality' => 'Bangkok', 'lat' =>	13.68	, 'long' =>	100.75	, 'elevation' =>	5	),	
	'CNX'=> array('name' => 'Chiang Mai International Airport', 'municipality' => 'Chiang Mai', 'lat' =>	18.77	, 'long' =>	98.96	, 'elevation' =>	1036	),	
	'DAD'=> array('name' => 'Da Nang International Airport', 'municipality' => 'Da Nang', 'lat' =>	16.04	, 'long' =>	108.20	, 'elevation' =>	33	),	
	'HAN'=> array('name' => 'Noi Bai International Airport', 'municipality' => 'Hanoi', 'lat' =>	21.22	, 'long' =>	105.81	, 'elevation' =>	39	),	
	'SGN'=> array('name' => 'Tan Son Nhat International Airport', 'municipality' => 'Ho Chi Minh City', 'lat' =>	10.82	, 'long' =>	106.65	, 'elevation' =>	33	),	
	'MDL'=> array('name' => 'Mandalay International Airport', 'municipality' => 'Mandalay', 'lat' =>	21.70	, 'long' =>	95.98	, 'elevation' =>	300	),	
	'RGN'=> array('name' => 'Yangon International Airport', 'municipality' => 'Yangon', 'lat' =>	16.91	, 'long' =>	96.13	, 'elevation' =>	109	),	
	'UPG'=> array('name' => 'Hasanuddin International Airport', 'municipality' => 'Ujung Pandang-Celebes Island', 'lat' =>	-5.06	, 'long' =>	119.55	, 'elevation' =>	47	),	
	'DPS'=> array('name' => 'Ngurah Rai (Bali) International Airport', 'municipality' => 'Denpasar-Bali Island', 'lat' =>	-8.75	, 'long' =>	115.17	, 'elevation' =>	14	),	
	'SUB'=> array('name' => 'Juanda International Airport', 'municipality' => 'Surabaya', 'lat' =>	-7.38	, 'long' =>	112.79	, 'elevation' =>	9	),	
	'SOQ'=> array('name' => 'Dominique Edward Osok Airport', 'municipality' => 'Sorong-Papua Island', 'lat' =>	-0.89	, 'long' =>	131.29	, 'elevation' =>	10	),	
	'BWN'=> array('name' => 'Brunei International Airport', 'municipality' => 'Bandar Seri Begawan', 'lat' =>	4.94	, 'long' =>	114.93	, 'elevation' =>	73	),	
	'CGK'=> array('name' => 'Soekarno-Hatta International Airport', 'municipality' => 'Jakarta', 'lat' =>	-6.13	, 'long' =>	106.66	, 'elevation' =>	34	),	
	'KUL'=> array('name' => 'Kuala Lumpur International Airport', 'municipality' => 'Kuala Lumpur', 'lat' =>	2.75	, 'long' =>	101.71	, 'elevation' =>	69	),	
	'SIN'=> array('name' => 'Singapore Changi International Airport', 'municipality' => 'Singapore', 'lat' =>	1.35	, 'long' =>	103.99	, 'elevation' =>	22	),	
	'BNE'=> array('name' => 'Brisbane International Airport', 'municipality' => 'Brisbane', 'lat' =>	-27.38	, 'long' =>	153.12	, 'elevation' =>	13	),	
	'MEL'=> array('name' => 'Melbourne International Airport', 'municipality' => 'Melbourne', 'lat' =>	-37.67	, 'long' =>	144.84	, 'elevation' =>	434	),	
	'PER'=> array('name' => 'Perth International Airport', 'municipality' => 'Perth', 'lat' =>	-31.94	, 'long' =>	115.97	, 'elevation' =>	67	),	
	'CBR'=> array('name' => 'Canberra International Airport', 'municipality' => 'Canberra', 'lat' =>	-35.31	, 'long' =>	149.20	, 'elevation' =>	1886	),	
	'SYD'=> array('name' => 'Sydney Kingsford Smith International Airport', 'municipality' => 'Sydney', 'lat' =>	-33.95	, 'long' =>	151.18	, 'elevation' =>	21	),	
	'PEK'=> array('name' => 'Beijing Capital International Airport', 'municipality' => 'Beijing', 'lat' =>	40.08	, 'long' =>	116.58	, 'elevation' =>	116	),	
	'NAY'=> array('name' => 'Beijing Nanyuan Airport', 'municipality' => 'Beijing', 'lat' =>	39.78	, 'long' =>	116.39	, 'elevation' => 'UNK'),	
	'TSN'=> array('name' => 'Tianjin Binhai International Airport', 'municipality' => 'Tianjin', 'lat' =>	39.12	, 'long' =>	117.35	, 'elevation' =>	10	),	
	'TYN'=> array('name' => 'Taiyuan Wusu Airport', 'municipality' => 'Taiyuan', 'lat' =>	37.75	, 'long' =>	112.63	, 'elevation' =>	2575	),	
	'CAN'=> array('name' => 'Guangzhou Baiyun International Airport', 'municipality' => 'Guangzhou', 'lat' =>	23.39	, 'long' =>	113.30	, 'elevation' =>	50	),	
	'CSX'=> array('name' => 'Changsha Huanghua International Airport', 'municipality' => 'Changsha', 'lat' =>	28.19	, 'long' =>	113.22	, 'elevation' =>	217	),	
	'KWL'=> array('name' => 'Guilin Liangjiang International Airport', 'municipality' => 'Guilin City', 'lat' =>	25.22	, 'long' =>	110.04	, 'elevation' =>	570	),	
	'NNG'=> array('name' => 'Nanning Wuxu Airport', 'municipality' => 'Nanning', 'lat' =>	22.61	, 'long' =>	108.17	, 'elevation' =>	421	),	
	'SZX'=> array('name' => 'Shenzhen Bao\'an International Airport', 'municipality' => 'Shenzhen', 'lat' =>	22.64	, 'long' =>	113.81	, 'elevation' =>	13	),	
	'CGO'=> array('name' => 'Zhengzhou Xinzheng International Airport', 'municipality' => 'Zhengzhou', 'lat' =>	34.52	, 'long' =>	113.84	, 'elevation' =>	495	),	
	'WUH'=> array('name' => 'Wuhan Tianhe International Airport', 'municipality' => 'Wuhan', 'lat' =>	30.78	, 'long' =>	114.21	, 'elevation' =>	113	),	
	'HAK'=> array('name' => 'Haikou Meilan International Airport', 'municipality' => 'Haikou', 'lat' =>	19.93	, 'long' =>	110.46	, 'elevation' =>	75	),	
	'SYX'=> array('name' => 'Sanya Phoenix International Airport', 'municipality' => 'Sanya', 'lat' =>	18.30	, 'long' =>	109.41	, 'elevation' =>	92	),	
	'XIY'=> array('name' => 'Xi\'an Xianyang International Airport', 'municipality' => 'Xianyang', 'lat' =>	34.45	, 'long' =>	108.75	, 'elevation' =>	1572	),	
	'KMG'=> array('name' => 'Kunming Changshui International Airport', 'municipality' => 'Kunming', 'lat' =>	25.10	, 'long' =>	102.93	, 'elevation' =>	6903	),	
	'XMN'=> array('name' => 'Xiamen Gaoqi International Airport', 'municipality' => 'Xiamen', 'lat' =>	24.54	, 'long' =>	118.13	, 'elevation' =>	59	),	
	'FOC'=> array('name' => 'Fuzhou Changle International Airport', 'municipality' => 'Fuzhou', 'lat' =>	25.94	, 'long' =>	119.66	, 'elevation' =>	46	),	
	'HGH'=> array('name' => 'Hangzhou Xiaoshan International Airport', 'municipality' => 'Hangzhou', 'lat' =>	30.23	, 'long' =>	120.43	, 'elevation' =>	23	),	
	'TNA'=> array('name' => 'Yaoqiang Airport', 'municipality' => 'Jinan', 'lat' =>	36.86	, 'long' =>	117.22	, 'elevation' =>	76	),	
	'NGB'=> array('name' => 'Ningbo Lishe International Airport', 'municipality' => 'Ningbo', 'lat' =>	29.83	, 'long' =>	121.46	, 'elevation' =>	13	),	
	'NKG'=> array('name' => 'Nanjing Lukou Airport', 'municipality' => 'Nanjing', 'lat' =>	31.74	, 'long' =>	118.86	, 'elevation' =>	49	),	
	'PVG'=> array('name' => 'Shanghai Pudong International Airport', 'municipality' => 'Shanghai', 'lat' =>	31.14	, 'long' =>	121.81	, 'elevation' =>	13	),	
	'SHA'=> array('name' => 'Shanghai Hongqiao International Airport', 'municipality' => 'Shanghai', 'lat' =>	31.20	, 'long' =>	121.34	, 'elevation' =>	10	),	
	'WNZ'=> array('name' => 'Wenzhou Yongqiang Airport', 'municipality' => 'Wenzhou', 'lat' =>	27.91	, 'long' =>	120.85	, 'elevation' => 'UNK'),	
	'CKG'=> array('name' => 'Chongqing Jiangbei International Airport', 'municipality' => 'Chongqing', 'lat' =>	29.72	, 'long' =>	106.64	, 'elevation' =>	1365	),	
	'KWE'=> array('name' => 'Longdongbao Airport', 'municipality' => 'Guiyang', 'lat' =>	26.54	, 'long' =>	106.80	, 'elevation' =>	3736	),	
	'CTU'=> array('name' => 'Chengdu Shuangliu International Airport', 'municipality' => 'Chengdu', 'lat' =>	30.58	, 'long' =>	103.95	, 'elevation' =>	1625	),	
	'URC'=> array('name' => '��r��mqi Diwopu International Airport', 'municipality' => '��r��mqi', 'lat' =>	43.91	, 'long' =>	87.47	, 'elevation' =>	2125	),	
	'HRB'=> array('name' => 'Taiping Airport', 'municipality' => 'Harbin', 'lat' =>	45.62	, 'long' =>	126.25	, 'elevation' =>	457	),	
	'DLC'=> array('name' => 'Zhoushuizi Airport', 'municipality' => 'Dalian', 'lat' =>	38.97	, 'long' =>	121.54	, 'elevation' =>	107	),	
	'SHE'=> array('name' => 'Taoxian Airport', 'municipality' => 'Shenyang', 'lat' =>	41.64	, 'long' =>	123.48	, 'elevation' =>	198	),
	//BeR 4pr18: adding manually Mauritius MRU airport details
	'MRU'=> array('name' => 'Sir Seewoosagur Ramgoolam Airport', 'municipality' => 'Port Louis', 'lat' =>	-20.43	, 'long' =>	57.68	, 'elevation' =>	187	),
	'SLL'=> array('name' => 'Salalah Airport', 'municipality' => 'Salalah', 'lat' =>	17.04	, 'long' =>	54.09	, 'elevation' =>	73	)
);
?>
